<?php
declare(strict_types=1);

namespace Refugio\Services;

use DateTimeImmutable;
use PDO;
use Refugio\Support\Money;
use RuntimeException;
use Throwable;

final class FinancialService
{
    public function __construct(private PDO $db) {}

    public function createAccount(array $input,int $userId):int
    {
        $name=mb_substr(trim(strip_tags((string)($input['nome']??''))),0,120);$type=(string)($input['tipo']??'');$types=['CAIXA','CONTA_CORRENTE','POUPANCA','CARTEIRA_DIGITAL','OUTRA'];
        if($name===''||!in_array($type,$types,true))throw new RuntimeException('Informe nome e tipo validos para a conta.');
        $balance=Money::normalize((string)($input['saldo_inicial']??'0'));$date=self::date((string)($input['data_saldo_inicial']??date('Y-m-d')));
        $s=$this->db->prepare('INSERT INTO contas_financeiras (nome,tipo,banco,agencia,conta,moeda,saldo_inicial,data_saldo_inicial) VALUES (?,?,?,?,?,?,?,?)');$s->execute([$name,$type,self::clean($input['banco']??'',100),self::clean($input['agencia']??'',30),self::clean($input['conta']??'',50),'BRL',$balance,$date]);$id=(int)$this->db->lastInsertId();$this->audit('CONTA_CRIADA','contas_financeiras',$id,['nome'=>$name],$userId);return $id;
    }

    public function createCategory(array $input,int $userId):int
    {
        $name=self::clean($input['nome']??'',120);$type=(string)($input['tipo']??'');if(!$name||!in_array($type,['RECEITA','DESPESA','AMBOS'],true))throw new RuntimeException('Categoria invalida.');
        $s=$this->db->prepare('INSERT INTO categorias_financeiras (parent_id,nome,tipo) VALUES (?,?,?)');$s->execute([!empty($input['parent_id'])?(int)$input['parent_id']:null,$name,$type]);$id=(int)$this->db->lastInsertId();$this->audit('CATEGORIA_CRIADA','categorias_financeiras',$id,['nome'=>$name,'tipo'=>$type],$userId);return$id;
    }

    public function createSupplier(array $input,int $userId):int
    {
        $name=self::clean($input['nome']??'',160);if(!$name)throw new RuntimeException('Informe o fornecedor.');$s=$this->db->prepare('INSERT INTO fornecedores (nome,documento,email,telefone,observacoes) VALUES (?,?,?,?,?)');$s->execute([$name,self::clean($input['documento']??'',20),filter_var($input['email']??'',FILTER_VALIDATE_EMAIL)?:null,self::clean($input['telefone']??'',30),self::clean($input['observacoes']??'',3000)]);$id=(int)$this->db->lastInsertId();$this->audit('FORNECEDOR_CRIADO','fornecedores',$id,['nome'=>$name],$userId);return$id;
    }

    public function createReceivable(array $input,int $userId):int
    {
        $description=self::clean($input['descricao']??'',255);$value=Money::normalize((string)($input['valor']??''));$due=self::date((string)($input['vencimento']??''));if(!$description||Money::toCents($value)<=0)throw new RuntimeException('Informe descricao, valor e vencimento validos.');
        $type=in_array($input['tipo']??'', ['SINAL','SALDO','INTEGRAL','CAUCAO','TAXA','OUTRO'],true)?$input['tipo']:'OUTRO';
        $s=$this->db->prepare('INSERT INTO contas_receber (reserva_id,cliente_id,categoria_id,conta_id,descricao,tipo,numero_parcela,total_parcelas,valor_original,vencimento,competencia,observacoes,criado_por) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([self::id($input['reserva_id']??null),self::id($input['cliente_id']??null),self::id($input['categoria_id']??null),self::id($input['conta_id']??null),$description,$type,self::id($input['numero_parcela']??null),self::id($input['total_parcelas']??null),$value,$due,!empty($input['competencia'])?self::date((string)$input['competencia']):null,self::clean($input['observacoes']??'',3000),$userId]);$id=(int)$this->db->lastInsertId();$this->audit('RECEBIVEL_CRIADO','contas_receber',$id,['valor'=>$value,'vencimento'=>$due],$userId);return$id;
    }

    public function receive(int $receivableId,array $input,int $userId,?string $forcedKey=null):int
    {
        $value=Money::normalize((string)($input['valor']??''));if(Money::toCents($value)<=0)throw new RuntimeException('O recebimento deve ser maior que zero.');$accountId=(int)($input['conta_id']??0);if($accountId<=0)throw new RuntimeException('Selecione a conta financeira.');$date=self::datetime((string)($input['recebido_em']??date('Y-m-d\TH:i')));$method=in_array($input['forma_pagamento']??'', ['PIX','DINHEIRO','TRANSFERENCIA','CARTAO','BOLETO','OUTRO'],true)?$input['forma_pagamento']:'OUTRO';$key=$forcedKey?:self::clean($input['idempotency_key']??'',190)?:bin2hex(random_bytes(16));
        $this->db->beginTransaction();try{$s=$this->db->prepare('SELECT * FROM contas_receber WHERE id=? FOR UPDATE');$s->execute([$receivableId]);$r=$s->fetch()?:throw new RuntimeException('Recebivel nao encontrado.');if(in_array($r['status'],['CANCELADO','ESTORNADO','RECEBIDO'],true))throw new RuntimeException('Este recebivel nao aceita novos pagamentos.');$remaining=Money::toCents((string)$r['valor_original'])-Money::toCents((string)$r['valor_recebido'])+Money::toCents((string)$r['valor_estornado']);if(Money::toCents($value)>$remaining)throw new RuntimeException('O valor excede o saldo do recebivel.');if($r['tipo']==='CAUCAO'&&Money::toCents($value)!==$remaining)throw new RuntimeException('O recebimento da caucao deve quitar o valor integral.');$i=$this->db->prepare('INSERT INTO recebimentos (conta_receber_id,conta_id,valor,forma_pagamento,recebido_em,referencia_externa,idempotency_key,observacoes,registrado_por) VALUES (?,?,?,?,?,?,?,?,?)');$i->execute([$receivableId,$accountId,$value,$method,$date,self::clean($input['referencia_externa']??'',190),$key,self::clean($input['observacoes']??'',3000),$userId]);$id=(int)$this->db->lastInsertId();$newReceived=Money::add((string)$r['valor_recebido'],$value);$newRemaining=$remaining-Money::toCents($value);$status=$newRemaining===0?'RECEBIDO':'PARCIAL';$this->db->prepare('UPDATE contas_receber SET valor_recebido=?,status=?,conta_id=? WHERE id=?')->execute([$newReceived,$status,$accountId,$receivableId]);$this->db->prepare("UPDATE caucoes SET recebimento_id=?,status='RECEBIDA',recebida_em=COALESCE(recebida_em,?) WHERE conta_receber_id=?")->execute([$id,$date,$receivableId]);$this->movement($accountId,'ENTRADA','RECEBIMENTO',$id,(string)$r['descricao'],$value,$date,$userId);$this->db->commit();$this->audit('RECEBIMENTO_REGISTRADO','recebimentos',$id,['recebivel_id'=>$receivableId,'valor'=>$value],$userId);return$id;}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();if(str_contains($e->getMessage(),'Duplicate entry')){$s=$this->db->prepare('SELECT id FROM recebimentos WHERE idempotency_key=?');$s->execute([$key]);return(int)$s->fetchColumn();}throw$e;}
    }

    public function createExpense(array $input,int $userId):int
    {
        $description=self::clean($input['descricao']??'',255);$value=Money::normalize((string)($input['valor']??''));$due=self::date((string)($input['vencimento']??''));if(!$description||Money::toCents($value)<=0)throw new RuntimeException('Informe descricao, valor e vencimento validos.');$s=$this->db->prepare('INSERT INTO contas_pagar (fornecedor_id,categoria_id,conta_id,descricao,documento,valor_original,vencimento,competencia,observacoes,criado_por) VALUES (?,?,?,?,?,?,?,?,?,?)');$s->execute([self::id($input['fornecedor_id']??null),self::id($input['categoria_id']??null),self::id($input['conta_id']??null),$description,self::clean($input['documento']??'',100),$value,$due,!empty($input['competencia'])?self::date((string)$input['competencia']):null,self::clean($input['observacoes']??'',3000),$userId]);$id=(int)$this->db->lastInsertId();$this->audit('DESPESA_CRIADA','contas_pagar',$id,['valor'=>$value,'vencimento'=>$due],$userId);return$id;
    }

    public function payExpense(int $expenseId,array $input,int $userId):int
    {
        $value=Money::normalize((string)($input['valor']??''));if(Money::toCents($value)<=0)throw new RuntimeException('O pagamento deve ser maior que zero.');$accountId=(int)($input['conta_id']??0);if($accountId<=0)throw new RuntimeException('Selecione a conta financeira.');$date=self::datetime((string)($input['pago_em']??date('Y-m-d\TH:i')));$method=in_array($input['forma_pagamento']??'', ['PIX','DINHEIRO','TRANSFERENCIA','CARTAO','BOLETO','DEBITO_AUTOMATICO','OUTRO'],true)?$input['forma_pagamento']:'OUTRO';$key=self::clean($input['idempotency_key']??'',190)?:bin2hex(random_bytes(16));
        $this->db->beginTransaction();try{$s=$this->db->prepare('SELECT * FROM contas_pagar WHERE id=? FOR UPDATE');$s->execute([$expenseId]);$r=$s->fetch()?:throw new RuntimeException('Despesa nao encontrada.');if(in_array($r['status'],['CANCELADO','ESTORNADO','PAGO'],true))throw new RuntimeException('Esta despesa nao aceita novos pagamentos.');$remaining=Money::toCents((string)$r['valor_original'])-Money::toCents((string)$r['valor_pago'])+Money::toCents((string)$r['valor_estornado']);if(Money::toCents($value)>$remaining)throw new RuntimeException('O valor excede o saldo da despesa.');$i=$this->db->prepare('INSERT INTO pagamentos_despesas (conta_pagar_id,conta_id,valor,forma_pagamento,pago_em,referencia_externa,idempotency_key,observacoes,registrado_por) VALUES (?,?,?,?,?,?,?,?,?)');$i->execute([$expenseId,$accountId,$value,$method,$date,self::clean($input['referencia_externa']??'',190),$key,self::clean($input['observacoes']??'',3000),$userId]);$id=(int)$this->db->lastInsertId();$newPaid=Money::add((string)$r['valor_pago'],$value);$status=$remaining-Money::toCents($value)===0?'PAGO':'PARCIAL';$this->db->prepare('UPDATE contas_pagar SET valor_pago=?,status=?,conta_id=? WHERE id=?')->execute([$newPaid,$status,$accountId,$expenseId]);$this->movement($accountId,'SAIDA','PAGAMENTO_DESPESA',$id,(string)$r['descricao'],$value,$date,$userId);$this->db->commit();$this->audit('DESPESA_PAGA','pagamentos_despesas',$id,['despesa_id'=>$expenseId,'valor'=>$value],$userId);return$id;}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
    }

    public function createRecurrence(array $input,int $userId):int
    {
        $description=self::clean($input['descricao']??'',255);$value=Money::normalize((string)($input['valor']??''));$period=(string)($input['periodicidade']??'');$start=self::date((string)($input['inicio']??''));if(!$description||Money::toCents($value)<=0||!in_array($period,['SEMANAL','MENSAL','BIMESTRAL','TRIMESTRAL','SEMESTRAL','ANUAL'],true))throw new RuntimeException('Recorrencia invalida.');$s=$this->db->prepare("INSERT INTO recorrencias_financeiras (tipo,fornecedor_id,categoria_id,conta_id,descricao,valor,periodicidade,intervalo_periodos,dia_vencimento,inicio,fim,proxima_competencia,criado_por) VALUES ('DESPESA',?,?,?,?,?,?,?,?,?,?,?,?)");$s->execute([self::id($input['fornecedor_id']??null),self::id($input['categoria_id']??null),self::id($input['conta_id']??null),$description,$value,$period,max(1,(int)($input['intervalo_periodos']??1)),self::id($input['dia_vencimento']??null),$start,!empty($input['fim'])?self::date((string)$input['fim']):null,$start,$userId]);$id=(int)$this->db->lastInsertId();$this->audit('RECORRENCIA_CRIADA','recorrencias_financeiras',$id,['valor'=>$value,'periodicidade'=>$period],$userId);return$id;
    }

    public function generateRecurrences(?DateTimeImmutable $until=null):int
    {
        $until??=new DateTimeImmutable('+45 days');$count=0;$rows=$this->db->query("SELECT * FROM recorrencias_financeiras WHERE ativa=1 AND proxima_competencia<='".$until->format('Y-m-d')."' ORDER BY id")->fetchAll();foreach($rows as$r){$this->db->beginTransaction();try{$lock=$this->db->prepare('SELECT * FROM recorrencias_financeiras WHERE id=? AND ativa=1 FOR UPDATE');$lock->execute([$r['id']]);$current=$lock->fetch();if(!$current){$this->db->rollBack();continue;}$competence=new DateTimeImmutable($current['proxima_competencia']);while($competence<=$until&&(!$current['fim']||$competence<=new DateTimeImmutable($current['fim']))){$day=(int)($current['dia_vencimento']?:$competence->format('d'));$last=(int)$competence->format('t');$due=$competence->setDate((int)$competence->format('Y'),(int)$competence->format('m'),min($day,$last));$s=$this->db->prepare('INSERT IGNORE INTO contas_pagar (fornecedor_id,categoria_id,conta_id,recorrencia_id,descricao,valor_original,vencimento,competencia,criado_por) VALUES (?,?,?,?,?,?,?,?,?)');$s->execute([$current['fornecedor_id'],$current['categoria_id'],$current['conta_id'],$current['id'],$current['descricao'],$current['valor'],$due->format('Y-m-d'),$competence->format('Y-m-01'),$current['criado_por']]);$count+=$s->rowCount();$competence=$this->nextPeriod($competence,$current['periodicidade'],(int)$current['intervalo_periodos']);}$this->db->prepare('UPDATE recorrencias_financeiras SET proxima_competencia=? WHERE id=?')->execute([$competence->format('Y-m-d'),$current['id']]);$this->db->commit();}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}return$count;
    }

    public function reconcile(array $input,int $userId):int
    {
        $accountId=(int)($input['conta_id']??0);$start=self::date((string)($input['data_inicio']??''));$end=self::date((string)($input['data_fim']??''));if($accountId<=0||$end<$start)throw new RuntimeException('Periodo de conciliacao invalido.');$statement=Money::normalize((string)($input['saldo_extrato']??''));$s=$this->db->prepare("SELECT cf.saldo_inicial+COALESCE(SUM(CASE WHEN m.tipo='ENTRADA' AND m.status='REALIZADO' THEN m.valor WHEN m.tipo='SAIDA' AND m.status='REALIZADO' THEN -m.valor ELSE 0 END),0) saldo FROM contas_financeiras cf LEFT JOIN movimentos_financeiros m ON m.conta_id=cf.id AND DATE(m.data_movimento)<=? WHERE cf.id=? GROUP BY cf.id");$s->execute([$end,$accountId]);$system=(string)($s->fetchColumn()?:'0.00');$difference=Money::subtract($statement,$system);$status=Money::toCents($difference)===0?'CONCILIADA':'ABERTA';$this->db->beginTransaction();try{$i=$this->db->prepare('INSERT INTO conciliacoes_financeiras (conta_id,data_inicio,data_fim,saldo_extrato,saldo_sistema,diferenca,status,observacoes,conciliado_por,conciliado_em) VALUES (?,?,?,?,?,?,?,?,?,?)');$i->execute([$accountId,$start,$end,$statement,$system,$difference,$status,self::clean($input['observacoes']??'',3000),$userId,$status==='CONCILIADA'?date('Y-m-d H:i:s'):null]);$id=(int)$this->db->lastInsertId();$item=$this->db->prepare('INSERT IGNORE INTO conciliacao_itens (conciliacao_id,movimento_id) VALUES (?,?)');foreach(array_map('intval',(array)($input['movimentos']??[]))as$movementId)if($movementId>0)$item->execute([$id,$movementId]);$this->db->commit();$this->audit('CONCILIACAO_CRIADA','conciliacoes_financeiras',$id,['diferenca'=>$difference,'status'=>$status],$userId);return$id;}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
    }

    public function cancelReceivable(int$id,string$reason,int$userId):void
    {
        $this->db->beginTransaction();try{$s=$this->db->prepare('SELECT * FROM contas_receber WHERE id=? FOR UPDATE');$s->execute([$id]);$row=$s->fetch()?:throw new RuntimeException('Recebivel nao encontrado.');if(Money::toCents((string)$row['valor_recebido'])>Money::toCents((string)$row['valor_estornado']))throw new RuntimeException('Estorne os recebimentos antes de cancelar.');$this->db->prepare("UPDATE contas_receber SET status='CANCELADO',cancelado_em=NOW(),observacoes=CONCAT_WS('\n',observacoes,?) WHERE id=?")->execute([self::clean($reason,1000),$id]);$this->db->commit();$this->audit('RECEBIVEL_CANCELADO','contas_receber',$id,['motivo'=>$reason],$userId);}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
    }

    public function cancelExpense(int$id,string$reason,int$userId):void
    {
        $this->db->beginTransaction();try{$s=$this->db->prepare('SELECT * FROM contas_pagar WHERE id=? FOR UPDATE');$s->execute([$id]);$row=$s->fetch()?:throw new RuntimeException('Despesa nao encontrada.');if(Money::toCents((string)$row['valor_pago'])>Money::toCents((string)$row['valor_estornado']))throw new RuntimeException('Estorne os pagamentos antes de cancelar.');$this->db->prepare("UPDATE contas_pagar SET status='CANCELADO',cancelado_em=NOW(),observacoes=CONCAT_WS('\n',observacoes,?) WHERE id=?")->execute([self::clean($reason,1000),$id]);$this->db->commit();$this->audit('DESPESA_CANCELADA','contas_pagar',$id,['motivo'=>$reason],$userId);}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
    }

    public function refundReceipt(int$id,string$value,string$reason,int$userId):void
    {
        $value=Money::normalize($value);$cents=Money::toCents($value);if($cents<=0)throw new RuntimeException('Informe um valor de estorno valido.');$this->db->beginTransaction();try{$s=$this->db->prepare('SELECT re.*,cr.valor_original,cr.valor_recebido,cr.valor_estornado total_estornado,cr.descricao FROM recebimentos re JOIN contas_receber cr ON cr.id=re.conta_receber_id WHERE re.id=? FOR UPDATE');$s->execute([$id]);$row=$s->fetch()?:throw new RuntimeException('Recebimento nao encontrado.');if($cents>Money::toCents((string)$row['valor'])-Money::toCents((string)$row['valor_estornado']))throw new RuntimeException('Estorno excede o valor disponivel.');$newRefund=Money::add((string)$row['valor_estornado'],$value);$this->db->prepare('UPDATE recebimentos SET valor_estornado=?,estornado_em=IF(?=valor,NOW(),estornado_em),observacoes=CONCAT_WS(\'\n\',observacoes,?) WHERE id=?')->execute([$newRefund,$newRefund,self::clean($reason,1000),$id]);$totalRefund=Money::add((string)$row['total_estornado'],$value);$netReceived=Money::subtract((string)$row['valor_recebido'],$totalRefund);$status=Money::toCents($netReceived)===0?'ESTORNADO':'PARCIAL';$this->db->prepare('UPDATE contas_receber SET valor_estornado=?,status=? WHERE id=?')->execute([$totalRefund,$status,$row['conta_receber_id']]);$this->db->prepare("UPDATE caucoes SET status='DEVOLVIDA',devolvida_em=NOW() WHERE recebimento_id=? AND valor_retido=0 AND ? >= valor")->execute([$id,$newRefund]);$this->movement((int)$row['conta_id'],'SAIDA','ESTORNO_RECEBIMENTO',$id,'Estorno: '.$row['descricao'],$value,date('Y-m-d H:i:s'),$userId);$this->db->commit();$this->audit('RECEBIMENTO_ESTORNADO','recebimentos',$id,['valor'=>$value,'motivo'=>$reason],$userId);}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
    }

    public function refundExpensePayment(int$id,string$value,string$reason,int$userId):void
    {
        $value=Money::normalize($value);$cents=Money::toCents($value);if($cents<=0)throw new RuntimeException('Informe um valor de estorno valido.');$this->db->beginTransaction();try{$s=$this->db->prepare('SELECT pd.*,cp.valor_original,cp.valor_pago,cp.valor_estornado total_estornado,cp.descricao FROM pagamentos_despesas pd JOIN contas_pagar cp ON cp.id=pd.conta_pagar_id WHERE pd.id=? FOR UPDATE');$s->execute([$id]);$row=$s->fetch()?:throw new RuntimeException('Pagamento de despesa nao encontrado.');if($cents>Money::toCents((string)$row['valor'])-Money::toCents((string)$row['valor_estornado']))throw new RuntimeException('Estorno excede o valor disponivel.');$newRefund=Money::add((string)$row['valor_estornado'],$value);$this->db->prepare('UPDATE pagamentos_despesas SET valor_estornado=?,estornado_em=IF(?=valor,NOW(),estornado_em),observacoes=CONCAT_WS(\'\n\',observacoes,?) WHERE id=?')->execute([$newRefund,$newRefund,self::clean($reason,1000),$id]);$totalRefund=Money::add((string)$row['total_estornado'],$value);$netPaid=Money::subtract((string)$row['valor_pago'],$totalRefund);$status=Money::toCents($netPaid)===0?'ESTORNADO':'PARCIAL';$this->db->prepare('UPDATE contas_pagar SET valor_estornado=?,status=? WHERE id=?')->execute([$totalRefund,$status,$row['conta_pagar_id']]);$this->movement((int)$row['conta_id'],'ENTRADA','ESTORNO_DESPESA',$id,'Estorno: '.$row['descricao'],$value,date('Y-m-d H:i:s'),$userId);$this->db->commit();$this->audit('PAGAMENTO_DESPESA_ESTORNADO','pagamentos_despesas',$id,['valor'=>$value,'motivo'=>$reason],$userId);}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
    }

    public function updateDeposit(int$id,string$action,string$value,string$reason,int$userId):void
    {
        $s=$this->db->prepare('SELECT * FROM caucoes WHERE id=?');$s->execute([$id]);$row=$s->fetch()?:throw new RuntimeException('Caucao nao encontrada.');if($action==='receber'){$receipt=$this->db->prepare('SELECT id,recebido_em FROM recebimentos WHERE conta_receber_id=? AND valor>valor_estornado ORDER BY recebido_em DESC,id DESC LIMIT 1');$receipt->execute([$row['conta_receber_id']]);$received=$receipt->fetch()?:throw new RuntimeException('Registre primeiro o recebimento financeiro da caucao.');$this->db->prepare("UPDATE caucoes SET recebimento_id=?,status='RECEBIDA',recebida_em=? WHERE id=?")->execute([$received['id'],$received['recebido_em'],$id]);}elseif($action==='devolver'){if(!in_array($row['status'],['RECEBIDA','RETIDA_PARCIAL'],true)||empty($row['recebimento_id']))throw new RuntimeException('A caucao ainda nao foi recebida.');$receipt=$this->db->prepare('SELECT valor_estornado FROM recebimentos WHERE id=?');$receipt->execute([$row['recebimento_id']]);$already=(string)($receipt->fetchColumn()?:'0.00');$refundable=Money::toCents((string)$row['valor'])-Money::toCents((string)$row['valor_retido'])-Money::toCents($already);if($refundable>0)$this->refundReceipt((int)$row['recebimento_id'],Money::fromCents($refundable),$reason?:'Devolucao de caucao',$userId);$this->db->prepare("UPDATE caucoes SET status='DEVOLVIDA',devolvida_em=NOW() WHERE id=?")->execute([$id]);}elseif($action==='reter'){$retained=Money::normalize($value);$cents=Money::toCents($retained);if(!in_array($row['status'],['RECEBIDA','RETIDA_PARCIAL'],true))throw new RuntimeException('A caucao ainda nao foi recebida.');if($cents<=0||$cents>Money::toCents((string)$row['valor']))throw new RuntimeException('Valor de retencao invalido.');$status=$cents===Money::toCents((string)$row['valor'])?'RETIDA_TOTAL':'RETIDA_PARCIAL';$this->db->prepare('UPDATE caucoes SET status=?,valor_retido=?,motivo_retencao=? WHERE id=?')->execute([$status,$retained,self::clean($reason,3000),$id]);}else throw new RuntimeException('Acao de caucao invalida.');$this->audit('CAUCAO_'.strtoupper($action),'caucoes',$id,['valor'=>$value,'motivo'=>$reason],$userId);
    }

    public function updateOverdueStatuses():int
    {
        $a=$this->db->exec("UPDATE contas_receber SET status='VENCIDO' WHERE status IN ('PENDENTE','PARCIAL') AND vencimento<CURDATE()");$b=$this->db->exec("UPDATE contas_pagar SET status='VENCIDO' WHERE status IN ('PENDENTE','PARCIAL') AND vencimento<CURDATE()");return$a+$b;
    }

    public function createDeposit(array $input,int $userId):int
    {
        $reservationId=(int)($input['reserva_id']??0);$value=Money::normalize((string)($input['valor']??''));if($reservationId<=0||Money::toCents($value)<=0)throw new RuntimeException('Informe reserva e valor da caucao.');$q=$this->db->prepare("SELECT id FROM contas_receber WHERE reserva_id=? AND tipo='CAUCAO' ORDER BY id LIMIT 1");$q->execute([$reservationId]);$receivableId=$q->fetchColumn();if(!$receivableId){$category=$this->db->query("SELECT id FROM categorias_financeiras WHERE nome='Caução' LIMIT 1")->fetchColumn()?:null;$this->db->prepare("INSERT INTO contas_receber (reserva_id,categoria_id,conta_id,descricao,tipo,valor_original,vencimento,criado_por) VALUES (?,?,?,?,'CAUCAO',?,CURDATE(),?)")->execute([$reservationId,$category,$this->defaultAccountId(),'Caucao da reserva #'.$reservationId,$value,$userId]);$receivableId=(int)$this->db->lastInsertId();}$receipt=$this->db->prepare('SELECT id FROM recebimentos WHERE conta_receber_id=? AND valor>valor_estornado ORDER BY id DESC LIMIT 1');$receipt->execute([$receivableId]);$receiptId=$receipt->fetchColumn()?:null;$s=$this->db->prepare("INSERT INTO caucoes (reserva_id,conta_receber_id,recebimento_id,valor,status,recebida_em,registrado_por) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE conta_receber_id=VALUES(conta_receber_id),recebimento_id=COALESCE(VALUES(recebimento_id),recebimento_id),valor=VALUES(valor),status=IF(VALUES(recebimento_id) IS NULL,status,'RECEBIDA'),recebida_em=IF(VALUES(recebimento_id) IS NULL,recebida_em,COALESCE(recebida_em,NOW())),registrado_por=VALUES(registrado_por),id=LAST_INSERT_ID(id)");$s->execute([$reservationId,$receivableId,$receiptId,$value,$receiptId?'RECEBIDA':'PENDENTE',$receiptId?date('Y-m-d H:i:s'):null,$userId]);$id=(int)$this->db->lastInsertId();$this->audit('CAUCAO_REGISTRADA','caucoes',$id,['valor'=>$value],$userId);return$id;
    }

    public function syncReservationPayments(int $reservationId,int $userId):void
    {
        $category=$this->db->query("SELECT id FROM categorias_financeiras WHERE nome='Hospedagem' LIMIT 1")->fetchColumn()?:null;$depositCategory=$this->db->query("SELECT id FROM categorias_financeiras WHERE nome='Caução' LIMIT 1")->fetchColumn()?:$category;$accountId=$this->defaultAccountId();$s=$this->db->prepare('SELECT p.*,r.codigo,rc.cliente_id FROM pagamentos p JOIN reservas r ON r.id=p.reserva_id LEFT JOIN reserva_contatos rc ON rc.reserva_id=r.id WHERE p.reserva_id=?');$s->execute([$reservationId]);foreach($s->fetchAll()as$p){$categoryId=$p['tipo']==='CAUCAO'?$depositCategory:$category;$this->db->prepare("INSERT INTO contas_receber (reserva_id,cliente_id,categoria_id,conta_id,pagamento_reserva_id,descricao,tipo,valor_original,vencimento,criado_por) VALUES (?,?,?,?,?,?,?,?,DATE(?),?) ON DUPLICATE KEY UPDATE valor_original=VALUES(valor_original),vencimento=VALUES(vencimento),descricao=VALUES(descricao)")->execute([$reservationId,$p['cliente_id'],$categoryId,$accountId,$p['id'],$p['tipo'].' da reserva '.$p['codigo'],$p['tipo'],$p['valor'],$p['data_vencimento'],$userId]);$receivableId=(int)$this->db->lastInsertId();if($receivableId===0){$q=$this->db->prepare('SELECT id FROM contas_receber WHERE pagamento_reserva_id=?');$q->execute([$p['id']]);$receivableId=(int)$q->fetchColumn();}if($p['status']==='CONFIRMADO'){$exists=$this->db->prepare('SELECT id FROM recebimentos WHERE idempotency_key=?');$key='reserva-payment-'.$p['id'];$exists->execute([$key]);if(!$exists->fetchColumn())$this->receive($receivableId,['valor'=>$p['valor'],'conta_id'=>$accountId,'forma_pagamento'=>'PIX','recebido_em'=>date('Y-m-d\TH:i',strtotime($p['data_confirmacao']?:'now')),'referencia_externa'=>'pagamento-reserva-'.$p['id']],$userId,$key);}if($p['tipo']==='CAUCAO')$this->createDeposit(['reserva_id'=>$reservationId,'valor'=>$p['valor']],$userId);}
    }

    private function defaultAccountId():int{$configured=(int)(\Refugio\Support\Env::int('FINANCIAL_DEFAULT_ACCOUNT_ID',0));if($configured>0)return$configured;$id=$this->db->query('SELECT id FROM contas_financeiras WHERE ativa=1 ORDER BY id LIMIT 1')->fetchColumn();if(!$id)throw new RuntimeException('Cadastre uma conta financeira padrao.');return(int)$id;}
    private function movement(int$accountId,string$type,string$origin,int$originId,string$description,string$value,string$date,int$userId):void{$this->db->prepare('INSERT INTO movimentos_financeiros (conta_id,tipo,origem_tipo,origem_id,descricao,valor,data_movimento,registrado_por) VALUES (?,?,?,?,?,?,?,?)')->execute([$accountId,$type,$origin,$originId,$description,$value,$date,$userId]);}
    private function nextPeriod(DateTimeImmutable$d,string$p,int$i):DateTimeImmutable{return match($p){'SEMANAL'=>$d->modify('+'.(7*$i).' days'),'MENSAL'=>$d->modify('+'.$i.' months'),'BIMESTRAL'=>$d->modify('+'.(2*$i).' months'),'TRIMESTRAL'=>$d->modify('+'.(3*$i).' months'),'SEMESTRAL'=>$d->modify('+'.(6*$i).' months'),'ANUAL'=>$d->modify('+'.$i.' years'),default=>$d->modify('+1 month')};}
    private function audit(string$a,string$e,int$id,array$after,int$user):void{(new AuditService($this->db))->record('FINANCEIRO',$a,$e,$id,null,$after,[],$user);}
    private static function clean(mixed$v,int$l):?string{$s=mb_substr(trim(strip_tags((string)$v)),0,$l);return$s===''?null:$s;}
    private static function id(mixed$v):?int{$i=(int)$v;return$i>0?$i:null;}
    private static function date(string$v):string{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new RuntimeException('Data invalida.');return$v;}
    private static function datetime(string$v):string{$d=DateTimeImmutable::createFromFormat('Y-m-d\TH:i',$v);if(!$d)throw new RuntimeException('Data e hora invalidas.');return$d->format('Y-m-d H:i:s');}
}
