<?php
declare(strict_types=1);

namespace Refugio\Services;

use DateTimeImmutable;
use PDO;
use Refugio\Marketing\MarketingProviderFactory;
use Refugio\Repositories\MarketingRepository;
use RuntimeException;
use Throwable;

final class MarketingSyncService
{
    private MarketingRepository $repository;
    public function __construct(private PDO$db){$this->repository=new MarketingRepository($db);}

    public function sync(int$integrationId,string$start,string$end,?int$userId=null):array
    {
        $from=self::date($start);$to=self::date($end);if($to<$from||$to>$from->modify('+366 days'))throw new RuntimeException('Periodo de sincronizacao invalido ou maior que 366 dias.');$integration=$this->repository->findIntegration($integrationId)??throw new RuntimeException('Integracao de marketing nao encontrada.');if($integration['status']==='DESCONECTADA')throw new RuntimeException('A integracao esta desconectada.');$lockName='marketing_sync_'.$integrationId;$lock=$this->db->prepare('SELECT GET_LOCK(?,0)');$lock->execute([$lockName]);if((int)$lock->fetchColumn()!==1)throw new RuntimeException('Ja existe uma sincronizacao em andamento para esta conta.');$syncId=0;
        try{$token=bin2hex(random_bytes(16));$s=$this->db->prepare("INSERT INTO marketing_sincronizacoes (integracao_id,tipo,data_inicio,data_fim,status,lock_token,iniciada_em) VALUES (?,?,?,?, 'EXECUTANDO',?,NOW())");$s->execute([$integrationId,'COMPLETA',$start,$end,$token]);$syncId=(int)$this->db->lastInsertId();$provider=MarketingProviderFactory::make($integration);if(!empty($integration['token_expires_at'])&&strtotime((string)$integration['token_expires_at'])<=time()+300&&$integration['provider']!=='META'){$tokens=$provider->refreshCredentials();$this->repository->updateCredentials($integrationId,$tokens);$integration=$this->repository->findIntegration($integrationId);$provider=MarketingProviderFactory::make($integration);}
            $stats=['processed'=>0,'created'=>0,'updated'=>0];$this->pages(fn($c)=>$provider->listCampaigns($c),fn($x)=>$this->upsertCampaign($integration,$x,$stats));$this->pages(fn($c)=>$provider->listAdGroups($c),fn($x)=>$this->upsertGroup($integration,$x,$stats));$this->pages(fn($c)=>$provider->listAds($c),fn($x)=>$this->upsertAd($integration,$x,$stats));$this->pages(fn($c)=>$provider->syncInsights($start,$end,$c),fn($x)=>$this->upsertMetric($integration,$x,$stats));
            $this->db->prepare("UPDATE marketing_sincronizacoes SET status='CONCLUIDA',registros_processados=?,registros_criados=?,registros_atualizados=?,finalizada_em=NOW() WHERE id=?")->execute([$stats['processed'],$stats['created'],$stats['updated'],$syncId]);$this->db->prepare("UPDATE marketing_integracoes SET status='CONECTADA',ultima_sincronizacao_em=NOW(),erro_ultima_sincronizacao=NULL WHERE id=?")->execute([$integrationId]);(new AuditService($this->db))->record('MARKETING','SINCRONIZAR','marketing_integracoes',$integrationId,null,['periodo'=>[$start,$end],'estatisticas'=>$stats],[],$userId);return$stats;
        }catch(Throwable$error){if($syncId)$this->db->prepare("UPDATE marketing_sincronizacoes SET status='FALHOU',erro=?,finalizada_em=NOW() WHERE id=?")->execute([mb_substr($error->getMessage(),0,4000),$syncId]);$this->db->prepare("UPDATE marketing_integracoes SET status='ERRO',erro_ultima_sincronizacao=? WHERE id=?")->execute([mb_substr($error->getMessage(),0,4000),$integrationId]);throw$error;}finally{$release=$this->db->prepare('SELECT RELEASE_LOCK(?)');$release->execute([$lockName]);}
    }

    public function test(int$id,int$userId):bool{$integration=$this->repository->findIntegration($id)??throw new RuntimeException('Integracao nao encontrada.');$ok=MarketingProviderFactory::make($integration)->testConnection();$this->db->prepare("UPDATE marketing_integracoes SET ultimo_teste_em=NOW(),status=?,erro_ultima_sincronizacao=? WHERE id=?")->execute([$ok?'CONECTADA':'ERRO',$ok?null:'Teste de conexao recusado',$id]);(new AuditService($this->db))->record('MARKETING','TESTAR_CONEXAO','marketing_integracoes',$id,null,['sucesso'=>$ok],[],$userId);return$ok;}
    private function pages(callable$fetch,callable$handle):void{$cursor=null;$pages=0;do{$page=$fetch($cursor);foreach($page['items']??[]as$item)$handle($item);$cursor=$page['next_cursor']??null;$pages++;if($pages>500)throw new RuntimeException('Limite de paginacao excedido durante a sincronizacao.');}while($cursor!==null&&$cursor!=='');}
    private function upsertCampaign(array$i,array$x,array&$stats):void{$s=$this->db->prepare('INSERT INTO marketing_campanhas (integracao_id,provider,external_id,nome,objetivo,status,data_inicio,data_fim,orcamento_diario,orcamento_total,moeda,dados_extras_json,last_synced_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),nome=VALUES(nome),objetivo=VALUES(objetivo),status=VALUES(status),data_inicio=VALUES(data_inicio),data_fim=VALUES(data_fim),orcamento_diario=VALUES(orcamento_diario),orcamento_total=VALUES(orcamento_total),moeda=VALUES(moeda),dados_extras_json=VALUES(dados_extras_json),last_synced_at=NOW()');$s->execute([$i['id'],$i['provider'],$x['external_id'],$x['name'],$x['objective']??null,$x['status']??null,self::datetime($x['start_at']??null),self::datetime($x['end_at']??null),$x['daily_budget']??null,$x['total_budget']??null,$x['currency']??$i['moeda'],self::json($x['extra']??[])]);$this->stat($s,$stats);}
    private function upsertGroup(array$i,array$x,array&$stats):void{$campaignId=$this->campaignId((int)$i['id'],(string)($x['campaign_external_id']??''));$s=$this->db->prepare('INSERT INTO marketing_grupos_anuncios (integracao_id,campanha_id,external_id,campanha_external_id,nome,status,orcamento,dados_extras_json,last_synced_at) VALUES (?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),campanha_id=VALUES(campanha_id),campanha_external_id=VALUES(campanha_external_id),nome=VALUES(nome),status=VALUES(status),orcamento=VALUES(orcamento),dados_extras_json=VALUES(dados_extras_json),last_synced_at=NOW()');$s->execute([$i['id'],$campaignId,$x['external_id'],$x['campaign_external_id']??null,$x['name'],$x['status']??null,$x['budget']??null,self::json($x['extra']??[])]);$this->stat($s,$stats);}
    private function upsertAd(array$i,array$x,array&$stats):void{$groupId=$this->groupId((int)$i['id'],(string)($x['group_external_id']??''));$s=$this->db->prepare('INSERT INTO marketing_anuncios (integracao_id,grupo_anuncio_id,external_id,grupo_external_id,nome,status,creative_name,creative_url,dados_extras_json,last_synced_at) VALUES (?,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),grupo_anuncio_id=VALUES(grupo_anuncio_id),grupo_external_id=VALUES(grupo_external_id),nome=VALUES(nome),status=VALUES(status),creative_name=VALUES(creative_name),creative_url=VALUES(creative_url),dados_extras_json=VALUES(dados_extras_json),last_synced_at=NOW()');$s->execute([$i['id'],$groupId,$x['external_id'],$x['group_external_id']??null,$x['name'],$x['status']??null,$x['creative_name']??null,$x['creative_url']??null,self::json($x['extra']??[])]);$this->stat($s,$stats);}
    private function upsertMetric(array$i,array$x,array&$stats):void{$campaignId=$this->campaignId((int)$i['id'],(string)($x['campaign_external_id']??''));$s=$this->db->prepare('INSERT INTO marketing_metricas_diarias (integracao_id,campanha_id,provider,nivel,external_entity_id,data,moeda,gasto,impressoes,alcance,cliques,conversoes,leads,valor_conversao,ctr,cpc,cpm,custo_por_lead,custo_por_conversao,frequencia,dados_extras_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE campanha_id=VALUES(campanha_id),moeda=VALUES(moeda),gasto=VALUES(gasto),impressoes=VALUES(impressoes),alcance=VALUES(alcance),cliques=VALUES(cliques),conversoes=VALUES(conversoes),leads=VALUES(leads),valor_conversao=VALUES(valor_conversao),ctr=VALUES(ctr),cpc=VALUES(cpc),cpm=VALUES(cpm),custo_por_lead=VALUES(custo_por_lead),custo_por_conversao=VALUES(custo_por_conversao),frequencia=VALUES(frequencia),dados_extras_json=VALUES(dados_extras_json),updated_at=NOW()');$s->execute([$i['id'],$campaignId,$i['provider'],$x['level']??'CAMPANHA',$x['external_entity_id'],$x['date'],$x['currency']??$i['moeda'],$x['spend']??null,$x['impressions']??null,$x['reach']??null,$x['clicks']??null,$x['conversions']??null,$x['leads']??null,$x['conversion_value']??null,$x['ctr']??null,$x['cpc']??null,$x['cpm']??null,$x['cost_per_lead']??null,$x['cost_per_conversion']??null,$x['frequency']??null,self::json($x['extra']??[])]);$this->stat($s,$stats);}
    private function stat(\PDOStatement$s,array&$stats):void{$stats['processed']++;if($s->rowCount()===1)$stats['created']++;else$stats['updated']++;}
    private function campaignId(int$i,string$external):?int{if($external==='')return null;$s=$this->db->prepare('SELECT id FROM marketing_campanhas WHERE integracao_id=? AND external_id=?');$s->execute([$i,$external]);$id=$s->fetchColumn();return$id===false?null:(int)$id;}
    private function groupId(int$i,string$external):?int{if($external==='')return null;$s=$this->db->prepare('SELECT id FROM marketing_grupos_anuncios WHERE integracao_id=? AND external_id=?');$s->execute([$i,$external]);$id=$s->fetchColumn();return$id===false?null:(int)$id;}
    private static function date(string$v):DateTimeImmutable{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new RuntimeException('Data de sincronizacao invalida.');return$d;}
    private static function datetime(mixed$v):?string{if(!$v)return null;try{return(new DateTimeImmutable((string)$v))->format('Y-m-d H:i:s');}catch(Throwable){return null;}}
    private static function json(array$v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
}
