<?php
declare(strict_types=1);

$config = require dirname(__DIR__) . '/bootstrap.php';
use Refugio\Models\ReservationStatus;
use Refugio\Models\ReviewStatus;
use Refugio\Services\AvailabilityService;
use Refugio\Services\ReviewEligibilityService;
use Refugio\Services\ReviewInviteService;
use Refugio\Services\ReviewService;
use Refugio\Services\NotificationService;
use Refugio\Services\UploadService;
use Refugio\Services\AuthorizationService;
use Refugio\Services\EncryptionService;
use Refugio\Services\ConversationService;
use Refugio\Services\WhatsAppWebhookService;
use Refugio\Services\AttributionService;
use Refugio\Services\PricingEngine;
use Refugio\Services\ICalendarService;
use Refugio\Services\ContractTemplateService;
use Refugio\Services\PdfRenderer;
use Refugio\Services\ReservationPdfTemplate;
use Refugio\Marketing\AbstractAdsProvider;
use Refugio\Support\ReservationValidator;
use Refugio\Support\ReviewValidator;
use Refugio\Support\Money;
use Refugio\Support\MarketingMetrics;

$passed = 0; $failed = 0;
function test(string $name, callable $callback): void {
    global $passed, $failed;
    try { $callback(); $passed++; fwrite(STDOUT, "[OK] {$name}\n"); }
    catch (Throwable $e) { $failed++; fwrite(STDERR, "[FALHA] {$name}: {$e->getMessage()}\n"); }
}
function expect(bool $condition, string $message='Condicao nao atendida'): void { if (!$condition) throw new RuntimeException($message); }

$valid = [
    'checkin'=>date('Y-m-d',strtotime('+10 days')), 'checkout'=>date('Y-m-d',strtotime('+12 days')),
    'adultos'=>'2','criancas'=>'1','nome'=>'Maria da Silva','cpf'=>'52998224725','email'=>'maria@example.com','telefone'=>'(16) 99999-9999',
    'regras_aceitas'=>'1','cancelamento_aceito'=>'1','contato_autorizado'=>'1','website'=>'',
];
test('solicitacao valida e telefone internacional', function() use ($valid,$config) { $r=ReservationValidator::validate($valid,$config); expect(!$r['errors']); expect($r['data']['telefone']==='5516999999999'); });
test('datas invalidas', function() use ($valid,$config) { $d=$valid; $d['checkout']=$d['checkin']; expect(isset(ReservationValidator::validate($d,$config)['errors']['checkout'])); });
test('limite de hospedes', function() use ($valid,$config) { $d=$valid; $d['adultos']='10'; $d['criancas']='1'; expect(isset(ReservationValidator::validate($d,$config)['errors']['hospedes'])); });
test('honeypot antispam', function() use ($valid,$config) { $d=$valid; $d['website']='spam'; expect(isset(ReservationValidator::validate($d,$config)['errors']['form'])); });
test('transicao de aprovacao valida', function() { expect(ReservationStatus::AGUARDANDO_APROVACAO->canTransitionTo(ReservationStatus::AGUARDANDO_PAGAMENTO)); });
test('transicao invalida bloqueada', function() { expect(!ReservationStatus::RECUSADA->canTransitionTo(ReservationStatus::RESERVA_CONFIRMADA)); try { ReservationStatus::RECUSADA->assertTransitionTo(ReservationStatus::RESERVA_CONFIRMADA); } catch (DomainException) { return; } throw new RuntimeException('Transicao foi aceita.'); });
test('estados que bloqueiam datas', function() { expect(in_array('RESERVA_CONFIRMADA',ReservationStatus::blocking(),true)); expect(!in_array('AGUARDANDO_APROVACAO',ReservationStatus::blocking(),true)); });
test('formula de sobreposicao presente', function() { $source=file_get_contents(BASE_PATH.'/app/Services/AvailabilityService.php'); expect(str_contains($source,'checkin < ? AND checkout > ?')); });
test('regra de sobreposicao de intervalos', function() { expect(AvailabilityService::overlaps('2026-08-10','2026-08-15','2026-08-14','2026-08-20')); expect(!AvailabilityService::overlaps('2026-08-10','2026-08-15','2026-08-15','2026-08-20')); });
test('aprovacao usa transacao e mutex', function() { $source=file_get_contents(BASE_PATH.'/app/Services/ReservationService.php'); expect(str_contains($source,'beginTransaction()')); expect(str_contains($source,'lockApprovalMutex()')); $migration=file_get_contents(BASE_PATH.'/database/migrations/001_create_reservas.sql'); expect(str_contains($migration,'reserva_mutex')); });
test('token publico nao usa id sequencial', function() { $source=file_get_contents(BASE_PATH.'/app/Services/ReservationService.php'); expect(str_contains($source,'random_bytes(32)')); });
test('rota administrativa exige autorizacao centralizada', function() { $source=file_get_contents(BASE_PATH.'/app/Controllers/AdminController.php'); expect(substr_count($source,'AuthorizationService::requirePermission')>=5); });
test('falhas de notificacao sao registradas sem rollback', function() { $source=file_get_contents(BASE_PATH.'/app/Services/NotificationService.php'); expect(str_contains($source,'catch (Throwable $e)')); expect(str_contains($source,'$this->failure')); });
test('upload malicioso recusado', function() use ($config) { $tmp=tempnam(sys_get_temp_dir(),'bad'); file_put_contents($tmp,"<?php echo 'x';"); try { (new UploadService($config['upload_max_bytes']))->receipt(['error'=>UPLOAD_ERR_OK,'size'=>filesize($tmp),'tmp_name'=>$tmp,'name'=>'ataque.jpg']); } catch (RuntimeException) { unlink($tmp); return; } unlink($tmp); throw new RuntimeException('Arquivo foi aceito.'); });
test('upload PNG valido', function() use ($config) { $tmp=tempnam(sys_get_temp_dir(),'png'); file_put_contents($tmp,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=')); $stored=(new UploadService($config['upload_max_bytes']))->receipt(['error'=>UPLOAD_ERR_OK,'size'=>filesize($tmp),'tmp_name'=>$tmp,'name'=>'ok.png']); expect($stored['mime']==='image/png'); unlink(BASE_PATH.'/'.$stored['path']); unlink($tmp); });
test('cron e idempotente por status', function() { $source=file_get_contents(BASE_PATH.'/app/Services/ReservationService.php'); expect(str_contains($source,'p.status IN {$paymentStatuses}')); expect(str_contains($source,"UPDATE reservas SET status='EXPIRADA'")); });
test('landing page contem entrada para reserva direta', function() { ob_start(); include BASE_PATH.'/index.php'; $html=(string)ob_get_clean(); expect(str_contains($html,'reserva/solicitar')); $dom=new DOMDocument(); @$dom->loadHTML($html); expect($dom->getElementsByTagName('html')->length===1); });
test('hero usa mp4 otimizado com poster e reproducao silenciosa', function() { $html=file_get_contents(BASE_PATH.'/index.php'); foreach(['assets/videos/IMG_0277.mp4','type="video/mp4"','autoplay','muted','loop','playsinline','poster="assets/images/imagens_a_rotacionar/Noturno.webp"'] as $needle) expect(str_contains($html,$needle)); expect(!str_contains($html,'assets/videos/IMG_0277.MOV')); expect(!str_contains($html,'class="hero-img"')); });
test('landing publica nao depende de helpers da aplicacao', function() { $html=file_get_contents(BASE_PATH.'/index.php'); expect(!str_contains($html,"e(base_url('contato/whatsapp'))")); expect(str_contains($html,'href="/contato/whatsapp"')); });
test('cards de comodidades permanecem visiveis sem javascript', function() { $css=file_get_contents(BASE_PATH.'/style.css'); expect((bool) preg_match('/\.comodidade-card\s*\{[^}]*opacity:\s*1\s*;/s',$css)); expect((bool) preg_match('/\.explore-card\s*\{[^}]*opacity:\s*1\s*;/s',$css)); expect(!str_contains($css,'.reveal-pending')); });
test('dashboard administrativo renderiza status centralizado', function() { $metrics=['pendentes'=>1,'pagamento'=>0,'comprovantes'=>0,'confirmadas'=>0,'proximas'=>0,'vencidos'=>0,'receita'=>0]; $recent=[['id'=>1,'codigo'=>'RDC-TESTE','nome_cliente'=>'Teste','checkin'=>'2026-08-10','checkout'=>'2026-08-12','status'=>'AGUARDANDO_APROVACAO']]; ob_start(); include BASE_PATH.'/app/Views/admin/dashboard.php'; $html=(string)ob_get_clean(); expect(str_contains($html,'Aguardando aprovacao')); expect(str_contains($html,'RDC-TESTE')); });

$reviewReservation = ['id'=>10,'nome_cliente'=>'Maria Aparecida Silva','status'=>'FINALIZADA','checkout'=>'2026-07-01','origem'=>'SITE_DIRETO'];
$reviewInput = [
    'nota_geral'=>'5','nota_limpeza'=>'4','nota_localizacao'=>'5','nota_conforto'=>'4','nota_comunicacao'=>'5','nota_custo_beneficio'=>'4',
    'comentario'=>'Uma estadia muito tranquila e agradável.','nome_exibicao_modo'=>'NOME_ABREVIADO','autoriza_publicacao'=>'1','website'=>'',
];
test('reserva direta finalizada e paga e elegivel', function() use ($reviewReservation) { $result=ReviewEligibilityService::evaluate($reviewReservation,true,false,new DateTimeImmutable('2026-07-22')); expect($result['eligible']); });
test('checkout futuro impede avaliacao', function() use ($reviewReservation) { $reservation=$reviewReservation; $reservation['checkout']='2026-08-01'; expect(!ReviewEligibilityService::evaluate($reservation,true,false,new DateTimeImmutable('2026-07-22'))['eligible']); });
test('reserva cancelada impede avaliacao', function() use ($reviewReservation) { $reservation=$reviewReservation; $reservation['status']='CANCELADA'; expect(!ReviewEligibilityService::evaluate($reservation,true,false,new DateTimeImmutable('2026-07-22'))['eligible']); });
test('pagamento nao confirmado impede avaliacao direta', function() use ($reviewReservation) { expect(!ReviewEligibilityService::evaluate($reviewReservation,false,false,new DateTimeImmutable('2026-07-22'))['eligible']); });
test('reserva externa finalizada pode ser validada pelo admin', function() use ($reviewReservation) { $reservation=$reviewReservation; $reservation['origem']='AIRBNB'; expect(ReviewEligibilityService::evaluate($reservation,false,false,new DateTimeImmutable('2026-07-22'))['eligible']); });
test('uma avaliacao por reserva', function() use ($reviewReservation) { expect(!ReviewEligibilityService::evaluate($reviewReservation,true,true,new DateTimeImmutable('2026-07-22'))['eligible']); $sql=file_get_contents(BASE_PATH.'/database/migrations/002_create_avaliacoes.sql'); expect(str_contains($sql,'UNIQUE KEY uk_avaliacao_reserva')); });
test('token de convite tem 256 bits e formato opaco', function() { $first=ReviewInviteService::generateToken(); $second=ReviewInviteService::generateToken(); expect((bool)preg_match('/^[a-f0-9]{64}$/',$first)); expect($first!==$second); });
test('token de convite e armazenado apenas como hash', function() { $token=ReviewInviteService::generateToken(); expect(ReviewInviteService::hashToken($token)===hash('sha256',$token)); $sql=file_get_contents(BASE_PATH.'/database/migrations/002_create_avaliacoes.sql'); expect(str_contains($sql,'token_hash CHAR(64)')); expect(!preg_match('/\btoken\s+VARCHAR/i',$sql)); });
test('historico de notificacao remove token do conteudo persistido', function() { $token=str_repeat('a',64); $redacted=NotificationService::redactReviewToken('https://example.test/avaliar/'.$token); expect(!str_contains($redacted,$token)); expect(str_contains($redacted,'[token-redacted]')); });
test('geracoes concorrentes nao rotacionam convite em processamento', function() { $now=new DateTimeImmutable('2026-07-22 12:00:00'); $invite=['status'=>'PENDENTE','expira_em'=>'2026-07-30 23:59:59','updated_at'=>'2026-07-22 11:59:00']; expect(ReviewInviteService::shouldSkipExistingInvite($invite,false,$now)); expect(!ReviewInviteService::shouldSkipExistingInvite($invite,true,$now)); });
test('convite pendente com falha antiga pode ser tentado novamente', function() { $now=new DateTimeImmutable('2026-07-22 12:00:00'); $invite=['status'=>'PENDENTE','expira_em'=>'2026-07-30 23:59:59','updated_at'=>'2026-07-22 10:00:00']; expect(!ReviewInviteService::shouldSkipExistingInvite($invite,false,$now)); });
test('formato de token valido e invalido', function() { expect(ReviewService::validTokenFormat(str_repeat('a',64))); expect(!ReviewService::validTokenFormat(str_repeat('a',63))); expect(!ReviewService::validTokenFormat(str_repeat('z',64))); });
test('convite valido pode ser utilizado', function() { $invite=['status'=>'ENVIADO','expira_em'=>'2026-07-30 23:59:59','revogado_em'=>null]; expect(ReviewService::usableInvitation($invite,new DateTimeImmutable('2026-07-22 12:00:00'))); });
test('convite expirado e recusado', function() { $invite=['status'=>'ENVIADO','expira_em'=>'2026-07-20 23:59:59','revogado_em'=>null]; expect(!ReviewService::usableInvitation($invite,new DateTimeImmutable('2026-07-22 12:00:00'))); });
test('convite revogado e recusado', function() { $invite=['status'=>'REVOGADO','expira_em'=>'2026-07-30 23:59:59','revogado_em'=>'2026-07-21 10:00:00']; expect(!ReviewService::usableInvitation($invite,new DateTimeImmutable('2026-07-22 12:00:00'))); });
test('convite utilizado e recusado', function() { $invite=['status'=>'UTILIZADO','expira_em'=>'2026-07-30 23:59:59','revogado_em'=>null]; expect(!ReviewService::usableInvitation($invite,new DateTimeImmutable('2026-07-22 12:00:00'))); });
test('todas as notas validas sao aceitas', function() use ($reviewReservation,$reviewInput) { $result=ReviewValidator::validate($reviewInput,$reviewReservation); expect(!$result['errors']); expect($result['data']['nota_geral']===5); });
test('nota fora de 1 a 5 e recusada', function() use ($reviewReservation,$reviewInput) { $input=$reviewInput; $input['nota_limpeza']='6'; expect(isset(ReviewValidator::validate($input,$reviewReservation)['errors']['nota_limpeza'])); });
test('comentario curto e recusado', function() use ($reviewReservation,$reviewInput) { $input=$reviewInput; $input['comentario']='curto'; expect(isset(ReviewValidator::validate($input,$reviewReservation)['errors']['comentario'])); });
test('consentimento de publicacao e obrigatorio', function() use ($reviewReservation,$reviewInput) { $input=$reviewInput; unset($input['autoriza_publicacao']); expect(isset(ReviewValidator::validate($input,$reviewReservation)['errors']['autoriza_publicacao'])); });
test('honeypot da avaliacao bloqueia bot', function() use ($reviewReservation,$reviewInput) { $input=$reviewInput; $input['website']='https://spam.invalid'; expect(isset(ReviewValidator::validate($input,$reviewReservation)['errors']['form'])); });
test('conteudo malicioso e sanitizado', function() use ($reviewReservation,$reviewInput) { $input=$reviewInput; $input['comentario']='<script>alert(1)</script> Experiencia suficientemente longa.'; $result=ReviewValidator::validate($input,$reviewReservation); expect(!str_contains($result['data']['comentario'],'<script>')); expect(!str_contains($result['data']['comentario'],'</script>')); });
test('nome abreviado nao expoe nome completo', function() use ($reviewReservation,$reviewInput) { $result=ReviewValidator::validate($reviewInput,$reviewReservation); expect($result['data']['nome_exibicao']==='Maria S.'); });
test('modo anonimo ignora nome do cliente', function() use ($reviewReservation,$reviewInput) { $input=$reviewInput; $input['anonima']='1'; $result=ReviewValidator::validate($input,$reviewReservation); expect($result['data']['nome_exibicao']==='Hóspede anônimo'); expect($result['data']['anonima']===1); });
test('moderacao aprova rejeita oculta e republica apenas em transicoes validas', function() { expect(ReviewStatus::PENDENTE->canTransitionTo(ReviewStatus::APROVADA)); expect(ReviewStatus::PENDENTE->canTransitionTo(ReviewStatus::REJEITADA)); expect(ReviewStatus::APROVADA->canTransitionTo(ReviewStatus::OCULTA)); expect(ReviewStatus::OCULTA->canTransitionTo(ReviewStatus::APROVADA)); expect(!ReviewStatus::PENDENTE->canTransitionTo(ReviewStatus::OCULTA)); });
test('moderacao preserva comentario original', function() { $source=file_get_contents(BASE_PATH.'/app/Services/ReviewService.php'); expect(!preg_match('/UPDATE avaliacoes SET comentario/i',$source)); expect(str_contains($source,'resposta_administrador')); });
test('submissao e transacional com bloqueio de convite e reserva', function() { $service=file_get_contents(BASE_PATH.'/app/Services/ReviewService.php'); $repository=file_get_contents(BASE_PATH.'/app/Repositories/ReviewRepository.php'); expect(str_contains($service,'beginTransaction()')); expect(str_contains($service,'invitationByToken($token,true)')); expect(str_contains($repository,'FOR UPDATE')); });
test('rotas administrativas de avaliacao exigem permissao e CSRF', function() { $source=file_get_contents(BASE_PATH.'/app/Controllers/AdminReviewController.php'); expect(substr_count($source,'AuthorizationService::requirePermission')>=4); expect(substr_count($source,'Csrf::verify')>=2); });
test('consulta publica filtra aprovacao e consentimento', function() { $source=file_get_contents(BASE_PATH.'/app/Repositories/ReviewRepository.php'); expect(substr_count($source,"status='APROVADA' AND a.autoriza_publicacao=1")>=1); expect(str_contains($source,"status='APROVADA' AND autoriza_publicacao=1")); });
test('api publica nao seleciona contato nem documento', function() { $source=file_get_contents(BASE_PATH.'/app/Repositories/ReviewRepository.php'); preg_match('/public function publicData.*?public function invitationCandidates/s',$source,$match); $public=$match[0]??''; expect(!str_contains($public,'r.email')); expect(!str_contains($public,'r.telefone')); expect(!str_contains($public,'cpf')); });
test('landing nao contem depoimentos inventados', function() { $html=file_get_contents(BASE_PATH.'/index.php'); foreach(['Mariana S.','Carlos M.','James L.','Santiago G.'] as $fake) expect(!str_contains($html,$fake)); expect(str_contains($html,'data-source="api/avaliacoes/publicas"')); });
test('carrossel cria texto sem inserir html da avaliacao', function() { $source=file_get_contents(BASE_PATH.'/assets/js/reviews-carousel.js'); expect(str_contains($source,'textContent')); expect(!str_contains($source,'innerHTML')); expect(str_contains($source,'Avaliação verificada')); });
test('estado vazio nao exibe media enganosa', function() { $html=file_get_contents(BASE_PATH.'/index.php'); expect(str_contains($html,'data-review-empty')); expect(!str_contains($html,'0.0 de 5')); $js=file_get_contents(BASE_PATH.'/assets/js/reviews-carousel.js'); expect(str_contains($js,'if (!items.length) return')); });
test('cron nao recria automaticamente convite expirado ou revogado', function() { $source=file_get_contents(BASE_PATH.'/app/Repositories/ReviewRepository.php'); expect(str_contains($source,"c.id IS NULL OR c.status='PENDENTE'")); expect(str_contains($source,"c.lembrete_enviado_em IS NULL")); });
test('migrations incluem tabelas e indices de avaliacao', function() { $sql=file_get_contents(BASE_PATH.'/database/migrations/002_create_avaliacoes.sql'); foreach(['convites_avaliacao','avaliacoes','idx_avaliacao_status','idx_avaliacao_nota','uk_convite_token'] as $needle) expect(str_contains($sql,$needle)); });

test('permissoes exatas e curingas sao centralizadas', function() { expect(AuthorizationService::permissionMatches('*','financeiro.manage')); expect(AuthorizationService::permissionMatches('conversas.*','conversas.reply')); expect(!AuthorizationService::permissionMatches('marketing.view','marketing.connect')); });
test('perfis iniciais e permissoes sao versionados', function() { $sql=file_get_contents(BASE_PATH.'/database/migrations/003_create_core_operacao.sql'); foreach(['SUPER_ADMIN','ATENDIMENTO','MARKETING','FINANCEIRO','LEITURA','usuarios_admin_perfis'] as $needle) expect(str_contains($sql,$needle)); });
test('criptografia exige OpenSSL ou faz roundtrip AES GCM', function() { $key=base64_encode(str_repeat('k',32)); if(!function_exists('openssl_encrypt')){try{new EncryptionService($key);}catch(RuntimeException $e){expect(str_contains($e->getMessage(),'OpenSSL'));return;}throw new RuntimeException('Ausencia de OpenSSL nao foi detectada.');}$service=new EncryptionService($key);$encrypted=$service->encrypt('segredo-123');expect($encrypted!=='segredo-123');expect(str_starts_with($encrypted,'v1:'));expect($service->decrypt($encrypted)==='segredo-123'); });
test('credencial adulterada e recusada quando OpenSSL esta disponivel', function() { if(!function_exists('openssl_encrypt'))return;$service=new EncryptionService(base64_encode(str_repeat('k',32)));$encrypted=$service->encrypt('segredo');$last=substr($encrypted,-1);$tampered=substr($encrypted,0,-1).($last==='A'?'B':'A');try{$service->decrypt($tampered);}catch(RuntimeException){return;}throw new RuntimeException('Credencial adulterada foi aceita.'); });
test('assinatura valida do webhook e aceita', function() { $body='{"object":"whatsapp_business_account"}';$secret='app-secret';$signature='sha256='.hash_hmac('sha256',$body,$secret);expect(WhatsAppWebhookService::validSignature($body,$signature,$secret)); });
test('assinatura falsa do webhook e recusada', function() { expect(!WhatsAppWebhookService::validSignature('{}','sha256='.str_repeat('0',64),'app-secret'));expect(!WhatsAppWebhookService::validSignature('{}','','app-secret')); });
test('mensagem de texto preserva tipo e conteudo', function() { [$type,$text]=WhatsAppWebhookService::messageData(['type'=>'text','text'=>['body'=>'Ola']]);expect($type==='TEXTO');expect($text==='Ola'); });
test('tipos de midia do WhatsApp preservam metadados', function() { foreach(['image'=>'IMAGEM','document'=>'DOCUMENTO','audio'=>'AUDIO','video'=>'VIDEO'] as$type=>$expected){$payload=['type'=>$type,$type=>['id'=>'media-1','mime_type'=>'application/octet-stream','filename'=>'arquivo.bin']];[$actual,,$media]=WhatsAppWebhookService::messageData($payload);expect($actual===$expected);expect($media==='media-1');} });
test('localizacao contato botao e interativa sao reconhecidos', function() { expect(WhatsAppWebhookService::messageData(['type'=>'location','location'=>['name'=>'Refugio']])[0]==='LOCALIZACAO');expect(WhatsAppWebhookService::messageData(['type'=>'contacts','contacts'=>[['name'=>['formatted_name'=>'Maria']]]])[0]==='CONTATO');expect(WhatsAppWebhookService::messageData(['type'=>'button','button'=>['text'=>'Sim']])[0]==='BOTAO');expect(WhatsAppWebhookService::messageData(['type'=>'interactive','interactive'=>['button_reply'=>['title'=>'Quero']]])[0]==='INTERATIVA'); });
test('evento e mensagem duplicados possuem chaves unicas', function() { $sql=file_get_contents(BASE_PATH.'/database/migrations/004_create_conversas.sql');expect(str_contains($sql,'uk_whatsapp_event_hash'));expect(str_contains($sql,'uk_mensagem_external')); });
test('texto livre respeita janela de 24 horas', function() { $now=new DateTimeImmutable('2026-07-22 12:00:00');expect(ConversationService::freeTextAllowed('2026-07-22 12:00:01',$now));expect(!ConversationService::freeTextAllowed('2026-07-22 11:59:59',$now));expect(!ConversationService::freeTextAllowed(null,$now)); });
test('webhook enfileira processamento pesado antes de responder', function() { $controller=file_get_contents(BASE_PATH.'/app/Controllers/WhatsAppWebhookController.php');$service=file_get_contents(BASE_PATH.'/app/Services/WhatsAppWebhookService.php');expect(str_contains($controller,"echo 'EVENT_RECEIVED'"));expect(str_contains($service,"enqueue('WHATSAPP_WEBHOOK'"));expect(str_contains($service,"enqueue('WHATSAPP_MEDIA'")); });
test('rotas de conversas exigem permissao e CSRF', function() { $source=file_get_contents(BASE_PATH.'/app/Controllers/ConversationController.php');expect(substr_count($source,'AuthorizationService::requirePermission')>=6);expect(substr_count($source,'Csrf::verify')>=2); });
test('midia enviada e preservada em armazenamento privado', function() { $source=file_get_contents(BASE_PATH.'/app/Services/ConversationService.php');expect(str_contains($source,'storeOutgoingMedia'));expect(str_contains($source,"BASE_PATH.'/storage/conversas/'"));expect(str_contains($source,'media_path=?')); });
test('auditoria de conversa nao duplica conteudo da nota', function() { $source=file_get_contents(BASE_PATH.'/app/Services/ConversationService.php');expect(str_contains($source,"['tamanho'=>mb_strlen(\$text)]"));expect(!str_contains($source,"'NOTA_INTERNA','conversas',\$id,null,['texto'=>\$text]")); });
test('valores monetarios decimais nao usam float', function() { foreach(['0,01'=>1,'1.234,56'=>123456,'9999999999.99'=>999999999999] as$value=>$cents)expect(Money::toCents($value)===$cents);expect(Money::add('10.10','0.20')==='10.30');expect(Money::subtract('10.00','3.33')==='6.67'); });
test('valor monetario invalido e recusado', function() { try{Money::toCents('1e4');}catch(InvalidArgumentException){return;}throw new RuntimeException('Notacao imprecisa foi aceita.'); });
test('financeiro usa DECIMAL e idempotencia', function() { $sql=file_get_contents(BASE_PATH.'/database/migrations/005_create_financeiro.sql');foreach(['DECIMAL(14,2)','uk_recebimento_idempotencia','uk_pagamento_despesa_idempotencia','movimentos_financeiros'] as$needle)expect(str_contains($sql,$needle));$service=file_get_contents(BASE_PATH.'/app/Services/FinancialService.php');expect(!str_contains($service,'(float)'));expect(str_contains($service,'beginTransaction()')); });
test('recorrencia financeira e idempotente por competencia', function() { $sql=file_get_contents(BASE_PATH.'/database/migrations/005_create_financeiro.sql');$service=file_get_contents(BASE_PATH.'/app/Services/FinancialService.php');expect(str_contains($sql,'uk_pagar_recorrencia_competencia'));expect(str_contains($service,'INSERT IGNORE INTO contas_pagar')); });
test('caucao fica separada da receita comum', function() { $sql=file_get_contents(BASE_PATH.'/database/migrations/005_create_financeiro.sql');expect(str_contains($sql,'CREATE TABLE IF NOT EXISTS caucoes'));expect(str_contains($sql,"'RETIDA_PARCIAL'"));expect(str_contains($sql,'uk_caucao_reserva')); });
test('caucao exige quitacao integral e devolucao movimenta caixa', function() { $service=file_get_contents(BASE_PATH.'/app/Services/FinancialService.php');expect(str_contains($service,"\$r['tipo']==='CAUCAO'"));expect(str_contains($service,"'SAIDA','ESTORNO_RECEBIMENTO'"));expect(str_contains($service,"status='DEVOLVIDA'")); });
test('exportacao CSV neutraliza formulas', function() { $source=file_get_contents(BASE_PATH.'/app/Controllers/FinancialController.php');expect(str_contains($source,"preg_match('/^[=+\\-@]/'"));expect(str_contains($source,'text/csv')); });
test('conversao de micros do Google preserva casas', function() { expect(AbstractAdsProvider::microsToDecimal('1234567')==='1.234567');expect(AbstractAdsProvider::microsToDecimal('1000000')==='1');expect(AbstractAdsProvider::microsToDecimal('1')==='0.000001'); });
test('metricas de marketing tratam divisao por zero', function() { expect(MarketingMetrics::cpl('10.00',0)===null);expect(MarketingMetrics::costPerReservation('100',4)===25.0);expect(MarketingMetrics::roas('500','100')===5.0);expect(MarketingMetrics::conversionRate(2,10)===20.0); });
test('atribuicao identifica os tres provedores', function() { expect(AttributionService::provider(['gclid'=>'x'])==='GOOGLE');expect(AttributionService::provider(['fbclid'=>'x'])==='META');expect(AttributionService::provider(['ttclid'=>'x'])==='TIKTOK');expect(AttributionService::provider([])==='DIRETO'); });
test('primeiro e ultimo contato sao persistidos separadamente', function() { $sql=file_get_contents(BASE_PATH.'/database/migrations/006_create_marketing.sql');expect(str_contains($sql,'first_touch_json JSON NOT NULL'));expect(str_contains($sql,'last_touch_json JSON NOT NULL'));$service=file_get_contents(BASE_PATH.'/app/Services/AttributionService.php');expect(str_contains($service,"_marketing_first_touch'] ??=")); });
test('sincronizacao de marketing usa lock e upsert', function() { $source=file_get_contents(BASE_PATH.'/app/Services/MarketingSyncService.php');expect(str_contains($source,'GET_LOCK'));expect(substr_count($source,'ON DUPLICATE KEY UPDATE')>=4);expect(str_contains($source,'RELEASE_LOCK')); });
test('adaptadores de marketing implementam interface comum', function() { foreach(['MetaAdsProvider','GoogleAdsProvider','TikTokAdsProvider']as$class){$source=file_get_contents(BASE_PATH.'/app/Marketing/'.$class.'.php');foreach(['listAccounts','listCampaigns','listAdGroups','listAds','getInsights','testConnection']as$method)expect(str_contains($source,'function '.$method));} });
test('versoes atuais das APIs sao configuraveis', function() { $env=file_get_contents(BASE_PATH.'/.env.example');foreach(['META_API_VERSION=v24.0','GOOGLE_ADS_API_VERSION=v24','TIKTOK_API_VERSION=v1.3','WHATSAPP_API_VERSION=v24.0']as$line)expect(str_contains($env,$line)); });
test('segredos e callbacks usam variaveis canonicas', function() { $env=file_get_contents(BASE_PATH.'/.env.example');foreach(['MARKETING_ENCRYPTION_KEY=','WHATSAPP_VERIFY_TOKEN=','META_REDIRECT_URI=','GOOGLE_ADS_REDIRECT_URI=','TIKTOK_ADS_REDIRECT_URI=','TIKTOK_ADS_APP_ID=']as$line)expect(str_contains($env,$line));expect(!str_contains($env,'APP_ENCRYPTION_KEY='));expect(!str_contains($env,'WHATSAPP_WEBHOOK_VERIFY_TOKEN=')); });
test('inicio do OAuth de marketing exige POST e CSRF', function() { $controller=file_get_contents(BASE_PATH.'/app/Controllers/MarketingController.php');$view=file_get_contents(BASE_PATH.'/app/Views/admin/marketing.php');expect(str_contains($controller,"REQUEST_METHOD']??'GET')!=='POST'"));expect(str_contains($controller,"Csrf::verify(\$_POST['_csrf']??null)"));expect(str_contains($view,"method=\"post\"")); });
test('tokens nao aparecem nas views administrativas', function() { foreach(glob(BASE_PATH.'/app/Views/admin/*.php')as$file){$source=file_get_contents($file);expect(!str_contains($source,'access_token_encrypted'),basename($file).' expoe token');expect(!str_contains($source,'refresh_token_encrypted'),basename($file).' expoe refresh token');} });
test('fila de jobs possui retry limitado e backoff', function() { $source=file_get_contents(BASE_PATH.'/app/Services/JobQueueService.php');$sql=file_get_contents(BASE_PATH.'/database/migrations/003_create_core_operacao.sql');expect(str_contains($source,'max_tentativas'));expect(str_contains($source,'2 **'));expect(str_contains($sql,'uk_job_chave')); });
test('menu administrativo contem as oito areas solicitadas', function() { $view=file_get_contents(BASE_PATH.'/app/Views/admin/_top.php');foreach(['Dashboard','Reservas','Clientes','Conversas','Marketing','Financeiro','Avaliações','Configurações']as$item)expect(str_contains($view,$item)); });
test('migrations possuem rollbacks versionados', function() { foreach(range(3,9)as$n)expect(count(glob(BASE_PATH.'/database/migrations/00'.$n.'_drop_*.sql'))===1); });

test('motor de precos calcula diarias limpeza e hospedes extras em centavos',function(){
    $result=(new PricingEngine())->calculate(['checkin'=>'2026-08-10','checkout'=>'2026-08-13','guests'=>6,'pets'=>0],[
        'base_daily_rate'=>'800.00','cleaning_fee'=>'280.00','guests_included_in_base_rate'=>4,'extra_guest_fee'=>'100.00','extra_guest_fee_mode'=>'PER_NIGHT','max_guests'=>10,'currency'=>'BRL','public_pricing_enabled'=>1,
    ]);
    expect($result['nights']===3);expect($result['subtotal']==='3280.00');expect($result['total']==='3280.00');expect(count($result['daily_rates'])===3);
});
test('motor publico falha fechado sem parametros comerciais',function(){try{(new PricingEngine())->calculate(['checkin'=>'2026-08-10','checkout'=>'2026-08-12','guests'=>2],['base_daily_rate'=>'800.00','cleaning_fee'=>'280.00','extra_guest_fee'=>'100.00','max_guests'=>10,'public_pricing_enabled'=>1]);}catch(DomainException $error){expect(str_contains($error->getMessage(),'GUESTS_INCLUDED_IN_BASE_RATE'));return;}throw new RuntimeException('Preço público incompleto foi calculado.');});
test('data especial substitui diaria base sem float',function(){$result=(new PricingEngine())->calculate(['checkin'=>'2026-12-24','checkout'=>'2026-12-26','guests'=>2],['base_daily_rate'=>'800.00','cleaning_fee'=>'0','guests_included_in_base_rate'=>2,'extra_guest_fee'=>'0','extra_guest_fee_mode'=>'PER_STAY','max_guests'=>10,'public_pricing_enabled'=>1],[],[['id'=>1,'nome'=>'Natal','starts_on'=>'2026-12-24','ends_on'=>'2026-12-25','daily_rate'=>'1200.00','priority'=>1,'ativo'=>1]]);expect($result['total']==='2400.00');});
test('parser ical desdobra linhas trata dia inteiro e cancelamento',function(){$reflection=new ReflectionClass(ICalendarService::class);$service=$reflection->newInstanceWithoutConstructor();$property=$reflection->getProperty('defaultTimezone');$property->setValue($service,'America/Sao_Paulo');$events=$service->parse("BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:abc-1\r\nDTSTART;VALUE=DATE:20260810\r\nDTEND;VALUE=DATE:20260812\r\nSUMMARY:Reserva\r\n externa\r\nSTATUS:CANCELLED\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n");expect(count($events)===1);expect($events[0]['uid']==='abc-1');expect($events[0]['all_day']);expect($events[0]['status']==='CANCELLED');expect($events[0]['summary']==='Reservaexterna');});
test('importador ical aceita redirecionamento relativo sem expor a fila no botao manual',function(){$reflection=new ReflectionClass(ICalendarService::class);$service=$reflection->newInstanceWithoutConstructor();$method=$reflection->getMethod('resolveRedirectUrl');$url=$method->invoke($service,'https://calendar.example.com/export/feed.ics?token=secret','../v2/calendar.ics?key=opaque');expect($url==='https://calendar.example.com/v2/calendar.ics?key=opaque');$controller=file_get_contents(BASE_PATH.'/app/Controllers/OperationsController.php');$start=strpos($controller,'private function calendarSourceSync');$end=strpos($controller,'private function calendarExportCreate',$start);$manual=substr($controller,$start,$end-$start);expect(str_contains($manual,'new ICalendarService'));expect(!str_contains($manual,'enqueue'));});
test('falha de url ical e registrada antes da tentativa de download',function(){$source=file_get_contents(BASE_PATH.'/app/Services/ICalendarService.php');$log=strpos($source,'INSERT INTO calendar_sync_logs');$fetch=strpos($source,'$this->fetch(');expect($log!==false&&$fetch!==false&&$log<$fetch);expect(str_contains($source,'MAX_REDIRECTS'));});
test('cadastro e worker disparam sincronizacao inicial e automatica do ical',function(){$controller=file_get_contents(BASE_PATH.'/app/Controllers/OperationsController.php');$worker=file_get_contents(BASE_PATH.'/scripts/process_jobs.php');$service=file_get_contents(BASE_PATH.'/app/Services/ICalendarService.php');expect(str_contains($controller,'syncSource((int)$this->db->lastInsertId())'));expect(str_contains($worker,'->enqueueDue($queue)'));expect(str_contains($service,'function enqueueDue'));});
test('painel informa quantidade e periodo dos bloqueios externos',function(){$admin=file_get_contents(BASE_PATH.'/app/Controllers/AdminController.php');$view=file_get_contents(BASE_PATH.'/app/Views/admin/calendar.php');foreach(['active_event_count','first_event_at','last_event_at']as$needle)expect(str_contains($admin,$needle));expect(str_contains($view,'bloqueio(s) ativo(s)'));expect(str_contains($view,'Período importado'));});
test('eventos externos exibem label e cor do provedor',function(){$service=file_get_contents(BASE_PATH.'/app/Services/UnifiedCalendarService.php');$view=file_get_contents(BASE_PATH.'/app/Views/admin/calendar.php');$css=file_get_contents(BASE_PATH.'/assets/css/admin-calendar.css');expect(str_contains($service,'s.ativo=1'));expect(str_contains($view,'$label=$external?'));expect(str_contains($view,"provider-'.e(strtolower"));foreach(['provider-airbnb','provider-booking','provider-google']as$needle)expect(str_contains($css,$needle));});
test('anexo dinamico sempre contem exatamente dez linhas de hospedes',function(){$rows=ContractTemplateService::guestRows([['full_name'=>'Maria']]);expect(substr_count($rows,'<tr>')===10);try{ContractTemplateService::guestRows(array_fill(0,11,['full_name'=>'X']));}catch(RuntimeException){return;}throw new RuntimeException('Mais de 10 hóspedes foram aceitos.');});
test('template contratual nao possui pagina editorial nem placeholders guillemet',function(){$template=file_get_contents(BASE_PATH.'/resources/contracts/contract-v2-suggested.html');expect(!str_contains($template,'Página 1 de 12'));expect(!preg_match('/«[^»]+»/u',$template));expect(str_contains($template,'{{guest_rows}}'));});
test('arquivo contratual preserva integralmente as doze paginas recebidas',function(){$archive=file_get_contents(BASE_PATH.'/resources/contracts/source-v1-archived.html');expect(str_contains($archive,'MODELO DE CONTRATO DE LOCAÇÃO POR TEMPORADA'));expect(str_contains($archive,'Página 1 de 12'));expect(str_contains($archive,'Página 12 de 12'));expect(str_contains($archive,'Código de Processo Civil, art. 784.'));});
test('tokens do portal sao redigidos de historicos',function(){$token=str_repeat('a',64);$safe=NotificationService::redactSensitiveTokens('Acesse https://example.test/minha-reserva/'.$token);expect(!str_contains($safe,$token));expect(str_contains($safe,'[token-redacted]'));});
test('schema da jornada contem snapshots hashes e restricoes',function(){$calendar=file_get_contents(BASE_PATH.'/database/migrations/007_create_calendar_pricing_quotes.sql');$journey=file_get_contents(BASE_PATH.'/database/migrations/008_create_guest_journey.sql');foreach(['calendar_external_events','calendar_holds','quote_items','quote_applied_rules','pricing_snapshot_json']as$needle)expect(str_contains($calendar,$needle));foreach(['guest_portal_tokens','token_encrypted','reservation_contracts','contract_events','reservation_guests','automation_runs']as$needle)expect(str_contains($journey,$needle));expect(substr_count($journey,"INSERT INTO automation_rules")===1);expect(substr_count($journey,"('REQUEST_RECEIVED'")===1);});
test('disponibilidade inclui reservas bloqueios externos e holds',function(){$source=file_get_contents(BASE_PATH.'/app/Services/AvailabilityService.php');foreach(['reservas','datas_bloqueadas','calendar_external_events','calendar_holds']as$needle)expect(str_contains($source,$needle));expect(str_contains($source,'hasConflicts'));});
test('worker reutiliza fila unica para ical contrato e automacoes',function(){$source=file_get_contents(BASE_PATH.'/scripts/process_jobs.php');foreach(['ICAL_SYNC','CONTRACT_PDF','RESERVATION_AUTOMATION']as$needle)expect(str_contains($source,$needle));expect(!str_contains($source,'new SecondQueue'));});
test('pedido whatsapp nasce pendente e reutiliza aprovacao transacional',function(){$service=file_get_contents(BASE_PATH.'/app/Services/ReservationService.php');$controller=file_get_contents(BASE_PATH.'/app/Controllers/WhatsAppReservationController.php');expect(str_contains($service,'createManualProposal'));expect(str_contains($service,'ReservationStatus::AGUARDANDO_APROVACAO'));expect(str_contains($controller,'->approve($id'));expect(str_contains($controller,'ReservationDocumentService::PAYMENT_REQUEST'));});
test('documentos de reserva sao versionados e armazenados de forma privada',function(){$sql=file_get_contents(BASE_PATH.'/database/migrations/009_create_whatsapp_reservation_documents.sql');foreach(['reservation_documents','reservation_document_deliveries','snapshot_json','sha256','uk_reservation_document_version']as$needle)expect(str_contains($sql,$needle));$service=file_get_contents(BASE_PATH.'/app/Services/ReservationDocumentService.php');expect(str_contains($service,"BASE_PATH . '/storage/reservation-documents/'"));expect(str_contains($service,"file_get_contents(\$path, false, null, 0, 5) !== '%PDF-'"));$htaccess=file_get_contents(BASE_PATH.'/.htaccess');expect(str_contains($htaccess,'storage|tests|resources'));});
test('anonimizacao remove snapshots e arquivos dos pedidos whatsapp',function(){$repository=file_get_contents(BASE_PATH.'/app/Repositories/CustomerRepository.php');expect(str_contains($repository,'DELETE FROM reservation_documents'));expect(str_contains($repository,"BASE_PATH . '/storage/reservation-documents'"));});
test('envio de pdf respeita janela do whatsapp e registra falha',function(){$conversation=file_get_contents(BASE_PATH.'/app/Services/ConversationService.php');$documents=file_get_contents(BASE_PATH.'/app/Services/ReservationDocumentService.php');expect(str_contains($conversation,'sendStoredDocument'));expect(str_contains($conversation,'freeTextAllowed'));expect(str_contains($documents,'janela_atendimento_ate>=NOW()'));expect(str_contains($documents,"status='FAILED'"));});
test('rotas dos pedidos whatsapp exigem csrf e autorizacao',function(){$controller=file_get_contents(BASE_PATH.'/app/Controllers/WhatsAppReservationController.php');$routes=file_get_contents(BASE_PATH.'/.htaccess');expect(str_contains($controller,'AuthorizationService::requirePermission'));expect(str_contains($controller,'Csrf::verify'));foreach(['pedidos-whatsapp/criar','gerar-proposta|enviar-proposta|aprovar-cobranca|gerar-cobranca|enviar-cobranca','pedidos-whatsapp/documentos']as$needle)expect(str_contains($routes,$needle));});
test('pdfs de proposta e pagamento possuem avisos operacionais',function(){$generator=file_get_contents(BASE_PATH.'/app/Services/ReservationPdfTemplate.php');foreach(['Pedido de reserva','Instruções de pagamento','ainda não confirma nem bloqueia','somente será confirmada após a identificação do pagamento','PIX COPIA E COLA']as$needle)expect(str_contains($generator,$needle));$view=file_get_contents(BASE_PATH.'/app/Views/admin/whatsapp-reservations.php');foreach(['valor_hospedagem','validade_proposta','politica_cancelamento']as$needle)expect(str_contains($view,$needle));});
test('geracao de pdf usa dompdf e nao depende de python',function(){$composer=json_decode(file_get_contents(BASE_PATH.'/composer.json'),true,512,JSON_THROW_ON_ERROR);expect(isset($composer['require']['dompdf/dompdf']));foreach(['app/Services/ContractPdfService.php','app/Services/ReservationDocumentService.php','scripts/process_jobs.php','.env.example']as$file){$source=file_get_contents(BASE_PATH.'/'.$file);expect(!str_contains($source,'PDF_PYTHON_BINARY'));expect(!str_contains($source,'proc_open'));}});
test('template php do pedido escapa dados do cliente',function(){$html=ReservationPdfTemplate::render(['document'=>['type'=>'PROPOSAL','version'=>1,'issued_at'=>'2026-07-30 12:00:00','valid_until'=>'2026-07-31 12:00:00'],'property'=>['name'=>'Refúgio'],'reservation'=>['code'=>'RDC-TESTE','customer_name'=>'<script>alert(1)</script> Maria','customer_phone'=>'5516999999999','checkin'=>'2026-08-10','checkout'=>'2026-08-12','nights'=>2,'adults'=>2,'children'=>0,'total'=>'1000.00'],'pricing_items'=>[['description'=>'Hospedagem','amount'=>'1000.00']]]);expect(str_contains($html,'Pedido de reserva'));expect(!str_contains($html,'<script>'));expect(str_contains($html,'R$ 1.000,00'));});
test('dompdf produz arquivo a4 valido pelo renderizador php',function(){$path=sys_get_temp_dir().'/refugio-dompdf-'.bin2hex(random_bytes(5)).'.pdf';try{(new PdfRenderer())->render('<!doctype html><html><head><meta charset="UTF-8"></head><body><h1>PDF Refúgio</h1><p>Validação do renderizador PHP.</p></body></html>',$path);expect(is_file($path));expect(file_get_contents($path,false,null,0,5)==='%PDF-');expect(filesize($path)>1000);}finally{if(is_file($path))unlink($path);}});

test('link privado do calendario sobrevive ao redirect e possui copia com fallback',function(){$controller=file_get_contents(BASE_PATH.'/app/Controllers/OperationsController.php');$view=file_get_contents(BASE_PATH.'/app/Views/admin/calendar.php');$script=file_get_contents(BASE_PATH.'/assets/js/admin.js');expect(str_contains($controller,"flash('calendar_export_url'"));expect(str_contains($view,"flash('calendar_export_url')"));expect(str_contains($view,'data-copy-target="calendar-export-url"'));expect(str_contains($script,'navigator.clipboard?.writeText'));expect(str_contains($script,"document.execCommand('copy')"));});
test('links privados do calendario podem ser revogados pelo painel',function(){$controller=file_get_contents(BASE_PATH.'/app/Controllers/OperationsController.php');$admin=file_get_contents(BASE_PATH.'/app/Controllers/AdminController.php');$view=file_get_contents(BASE_PATH.'/app/Views/admin/calendar.php');expect(str_contains($controller,"'calendar-export-revoke'"));expect(str_contains($controller,'SET ativo=0,revoked_at=NOW()'));expect(str_contains($admin,'FROM calendar_export_tokens'));expect(str_contains($view,'calendar-export-revoke'));});

fwrite(STDOUT, "\n{$passed} teste(s) passaram; {$failed} falharam.\n");
exit($failed ? 1 : 0);
