<?php declare(strict_types=1); $title='Conversas'; require BASE_PATH.'/app/Views/admin/_top.php'; ?>
<section class="page-heading conversations-heading">
    <div><p class="eyebrow">Atendimento WhatsApp</p><h1>Conversas</h1><p><?= (int)$result['total'] ?> conversa(s) na caixa de entrada</p></div>
    <?php if(can('conversas.manage')): ?><form action="<?= e(base_url('admin/conversas/templates/sincronizar')) ?>" method="post"><?= csrf_field() ?><button class="admin-secondary" type="submit">Sincronizar templates</button></form><?php endif; ?>
</section>
<form class="conversation-filters" method="get" action="<?= e(base_url('admin/conversas')) ?>">
    <input type="search" name="q" placeholder="Nome, telefone ou mensagem" value="<?= e($filters['q']??'') ?>">
    <select name="status"><option value="">Todos os status</option><?php foreach(['NOVA','EM_ATENDIMENTO','AGUARDANDO_CLIENTE','AGUARDANDO_EQUIPE','CONVERTIDA','FINALIZADA','ARQUIVADA','SPAM'] as $value): ?><option value="<?= e($value) ?>" <?= ($filters['status']??'')===$value?'selected':'' ?>><?= e(str_replace('_',' ',$value)) ?></option><?php endforeach; ?></select>
    <select name="atendente_id"><option value="">Todos os atendentes</option><?php foreach($agents as $agent): ?><option value="<?= (int)$agent['id'] ?>" <?= (string)($filters['atendente_id']??'')===(string)$agent['id']?'selected':'' ?>><?= e($agent['nome']) ?></option><?php endforeach; ?></select>
    <button class="admin-primary" type="submit">Filtrar</button>
</form>
<section class="conversation-layout <?= $conversation?'has-selected':'' ?>" data-conversation-app data-conversation-id="<?= (int)($conversation['id']??0) ?>" data-poll-url="<?= $conversation?e(base_url('admin/conversas/'.$conversation['id'].'/poll')):'' ?>" data-poll-interval="<?= (int)($this->config['conversations_realtime_interval_seconds']??10)*1000 ?>">
    <aside class="conversation-list" aria-label="Lista de conversas">
        <?php if(!$result['items']): ?><div class="empty-state"><strong>Nenhuma conversa</strong><p>As novas mensagens aparecerão aqui após o webhook ser configurado.</p></div><?php endif; ?>
        <?php foreach($result['items'] as $item): ?><a class="conversation-list-item <?= $conversation&&(int)$item['id']===(int)$conversation['id']?'active':'' ?>" href="<?= e(base_url('admin/conversas?id='.$item['id'])) ?>">
            <span class="conversation-avatar"><?= e(mb_substr($item['nome_contato']?:$item['telefone_normalizado'],0,1)) ?></span>
            <span class="conversation-summary"><strong><?= e($item['nome_contato']?:$item['cliente_nome']?:$item['telefone_normalizado']) ?></strong><small><?= e($item['ultima_mensagem_preview']?:'Sem mensagem') ?></small><em><?= e($item['tags']??'') ?></em></span>
            <span class="conversation-meta"><time><?= e($item['ultima_mensagem_em']?date('d/m H:i',strtotime($item['ultima_mensagem_em'])):'') ?></time><?php if((int)$item['nao_lidas']>0): ?><b><?= (int)$item['nao_lidas'] ?></b><?php endif; ?><small><?= e(str_replace('_',' ',$item['status'])) ?></small></span>
        </a><?php endforeach; ?>
    </aside>
    <?php if($conversation): ?>
    <section class="conversation-thread">
        <header><button class="mobile-back" type="button" data-conversation-back>← Caixa</button><div><strong><?= e($conversation['nome_contato']?:$conversation['cliente_nome']?:$conversation['telefone_normalizado']) ?></strong><small><?= e($conversation['telefone_normalizado']) ?> · <?= e(str_replace('_',' ',$conversation['status'])) ?></small></div><button type="button" class="admin-secondary" data-copy-phone="<?= e($conversation['telefone_normalizado']) ?>">Copiar telefone</button></header>
        <div class="message-stream" data-message-stream data-last-message-id="<?= (int)($messages?end($messages)['id']:0) ?>" aria-live="polite">
            <?php $day=''; foreach($messages as $message): $messageDay=date('Y-m-d',strtotime($message['recebida_em']?:$message['enviada_em']?:$message['created_at'])); if($messageDay!==$day):$day=$messageDay;?><div class="message-day"><?= e(date('d/m/Y',strtotime($day))) ?></div><?php endif; ?>
            <article class="message-bubble <?= $message['direcao']==='SAIDA'?'outgoing':'incoming' ?>" data-message-id="<?= (int)$message['id'] ?>">
                <small><?= e($message['tipo']) ?></small><?php if($message['texto']): ?><p><?= nl2br(e($message['texto'])) ?></p><?php endif; ?>
                <?php if($message['media_path']||$message['media_id']): $mediaUrl=base_url('admin/conversas/midia/'.$message['id']); $isImage=$message['tipo']==='IMAGEM'||$message['tipo']==='STICKER'||str_starts_with((string)$message['media_mime'],'image/'); $isAudio=$message['tipo']==='AUDIO'||str_starts_with((string)$message['media_mime'],'audio/'); ?><?php if($isImage): ?><a href="<?= e($mediaUrl) ?>" target="_blank" rel="noopener"><img src="<?= e($mediaUrl) ?>" alt="Imagem recebida" loading="lazy"></a><?php elseif($isAudio): ?><audio controls preload="metadata" src="<?= e($mediaUrl) ?>">Seu navegador não suporta áudio.</audio><?php else: ?><a href="<?= e($mediaUrl) ?>" target="_blank" rel="noopener">Abrir <?= e($message['media_nome']?:'anexo') ?></a><?php endif; ?><?php endif; ?>
                <footer><?= e(date('H:i',strtotime($message['recebida_em']?:$message['enviada_em']?:$message['created_at']))) ?><?php if($message['direcao']==='SAIDA'): ?> · <?= e($message['status']) ?><?php endif; ?><?php if($message['usuario_nome']): ?> · <?= e($message['usuario_nome']) ?><?php endif; ?></footer>
                <?php if($message['erro']): ?><span class="message-error"><?= e($message['erro']) ?></span><?php if(can('conversas.reply')&&in_array($message['tipo'],['TEXTO','TEMPLATE'],true)):?><form action="<?= e(base_url('admin/conversas/'.$conversation['id'].'/reenviar')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="mensagem_id" value="<?= (int)$message['id'] ?>"><button class="admin-secondary" type="submit">Tentar novamente</button></form><?php endif;?><?php endif; ?>
                <button class="message-reply" type="button" data-reply-message="<?= (int)$message['id'] ?>">Responder</button>
            </article><?php endforeach; ?>
        </div>
        <?php if(can('conversas.reply')): ?><div class="conversation-composer">
            <?php if(Refugio\Services\ConversationService::freeTextAllowed($conversation['janela_atendimento_ate'])): ?>
            <div class="conversation-ai-tools">
                <button class="admin-secondary" type="button" data-ai-suggest data-ai-url="<?= e(base_url('admin/conversas/'.$conversation['id'].'/sugerir-ia')) ?>" data-ai-csrf="<?= e(Refugio\Support\Csrf::token()) ?>" aria-controls="conversation-text" <?= empty($conversationAiConfigured)?'disabled':'' ?>>Sugerir resposta com IA</button>
                <span data-ai-feedback role="status" aria-live="polite"><?= empty($conversationAiConfigured)?'Configure OPENAI_API_KEY para habilitar.':'A IA usa calendário, preços e dados atuais. Revise antes de enviar.' ?></span>
                <?php if(!empty($conversationAiConfigured)): ?><small><?= e($conversationAiModel??'') ?></small><?php endif; ?>
            </div>
            <form action="<?= e(base_url('admin/conversas/'.$conversation['id'].'/enviar')) ?>" method="post" class="composer-form"><?= csrf_field() ?><input type="hidden" name="respondendo_a_id" data-reply-input><label class="sr-only" for="conversation-text">Mensagem</label><textarea id="conversation-text" name="texto" rows="2" maxlength="4096" required placeholder="Digite uma mensagem"></textarea><button class="admin-primary" type="submit">Enviar</button></form>
            <details><summary>Enviar mídia</summary><form action="<?= e(base_url('admin/conversas/'.$conversation['id'].'/midia')) ?>" method="post" enctype="multipart/form-data" class="admin-form"><?= csrf_field() ?><input type="file" name="arquivo" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,audio/ogg,audio/mpeg,video/mp4" required><input name="legenda" maxlength="1024" placeholder="Legenda opcional"><button class="admin-secondary">Enviar mídia</button></form></details>
            <?php else: ?><div class="admin-alert warning">A janela de 24 horas encerrou. Use um template aprovado para retomar o contato.</div><?php endif; ?>
            <details><summary>Enviar template</summary><form action="<?= e(base_url('admin/conversas/'.$conversation['id'].'/template')) ?>" method="post" class="admin-form"><?= csrf_field() ?><select name="template_id" required><option value="">Selecione</option><?php foreach($templates as $template): ?><option value="<?= (int)$template['id'] ?>"><?= e($template['nome'].' · '.$template['idioma']) ?></option><?php endforeach; ?></select><textarea name="parametros" rows="3" placeholder="Um parâmetro por linha"></textarea><button class="admin-secondary">Enviar template</button></form></details>
        </div><?php endif; ?>
    </section>
    <aside class="conversation-contact">
        <section><p class="eyebrow">Contato</p><h2><?= e($conversation['cliente_nome']?:$conversation['lead_nome']?:'Novo contato') ?></h2><dl><dt>Telefone</dt><dd><?= e($conversation['telefone_normalizado']) ?></dd><dt>Origem</dt><dd><?= e($conversation['origem']?:'—') ?></dd><dt>Campanha</dt><dd><?= e($conversation['utm_campaign']?:'—') ?></dd><dt>Reserva</dt><dd><?= $conversation['reserva_id']?'<a href="'.e(base_url('admin/reservas/'.$conversation['reserva_id'])).'">'.e($conversation['reserva_codigo']).'</a>':'—' ?></dd></dl></section>
        <?php if(can('conversas.manage')): ?><form action="<?= e(base_url('admin/conversas/'.$conversation['id'].'/atualizar')) ?>" method="post" class="admin-form compact"><?= csrf_field() ?>
            <label>Status<select name="status"><?php foreach(['NOVA','EM_ATENDIMENTO','AGUARDANDO_CLIENTE','AGUARDANDO_EQUIPE','CONVERTIDA','FINALIZADA','ARQUIVADA','SPAM'] as $value): ?><option <?= $conversation['status']===$value?'selected':'' ?>><?= e($value) ?></option><?php endforeach; ?></select></label>
            <label>Prioridade<select name="prioridade"><?php foreach(['BAIXA','NORMAL','ALTA','URGENTE'] as $value): ?><option <?= $conversation['prioridade']===$value?'selected':'' ?>><?= e($value) ?></option><?php endforeach; ?></select></label>
            <label>Atendente<select name="atendente_id"><option value="">Não atribuído</option><?php foreach($agents as $agent): ?><option value="<?= (int)$agent['id'] ?>" <?= (int)$conversation['atendente_id']===(int)$agent['id']?'selected':'' ?>><?= e($agent['nome']) ?></option><?php endforeach; ?></select></label>
            <label>Cliente ID<input type="number" name="cliente_id" min="1" value="<?= e($conversation['cliente_id']??'') ?>"></label><label>Reserva ID<input type="number" name="reserva_id" min="1" value="<?= e($conversation['reserva_id']??'') ?>"></label>
            <fieldset><legend>Tags</legend><?php foreach($tags as $tag): ?><label class="check-row"><input type="checkbox" name="tags[]" value="<?= (int)$tag['id'] ?>" <?= in_array((int)$tag['id'],$assignedTags,true)?'checked':'' ?>><span style="--tag-color:<?= e($tag['cor']) ?>"><?= e($tag['nome']) ?></span></label><?php endforeach; ?></fieldset>
            <button class="admin-primary">Salvar atendimento</button>
        </form><?php endif; ?>
        <details><summary>Notas internas</summary><?php if(can('conversas.manage')): ?><form action="<?= e(base_url('admin/conversas/'.$conversation['id'].'/nota')) ?>" method="post" class="admin-form"><?= csrf_field() ?><textarea name="nota" maxlength="2000" required></textarea><button class="admin-secondary">Adicionar nota</button></form><?php endif; ?><?php foreach($notes as $note): ?><article class="internal-note"><p><?= nl2br(e($note['texto'])) ?></p><small><?= e($note['usuario_nome']?:'Sistema') ?> · <?= e(date('d/m/Y H:i',strtotime($note['created_at']))) ?></small></article><?php endforeach; ?></details>
        <?php if(can('reservas.create')): ?><details><summary>Criar solicitação de reserva</summary><form action="<?= e(base_url('admin/conversas/'.$conversation['id'].'/criar-reserva')) ?>" method="post" class="admin-form compact"><?= csrf_field() ?><input name="nome" value="<?= e($conversation['nome_contato']?:$conversation['cliente_nome']?:'') ?>" placeholder="Nome" required><input type="email" name="email" value="<?= e($conversation['cliente_email']??'') ?>" placeholder="E-mail" required><label>Check-in<input type="date" name="checkin" min="<?= date('Y-m-d') ?>" required></label><label>Check-out<input type="date" name="checkout" min="<?= date('Y-m-d',strtotime('+1 day')) ?>" required></label><input type="number" name="adultos" min="1" value="1" required><input type="number" name="criancas" min="0" value="0" required><textarea name="observacoes" placeholder="Observações"></textarea><button class="admin-primary">Criar solicitação</button></form></details><?php endif; ?>
    </aside>
    <?php else: ?><div class="conversation-empty empty-state"><h2>Selecione uma conversa</h2><p>O histórico e os dados do contato aparecerão aqui.</p></div><?php endif; ?>
</section>
<script src="<?= e(base_url('assets/js/conversations.js?v=3')) ?>" defer></script>
<?php require BASE_PATH.'/app/Views/admin/_bottom.php'; ?>
