-- Integracoes e atribuicao de marketing (leitura e analise).
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS marketing_integracoes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    provider VARCHAR(16) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    conta_externa_id VARCHAR(190) NULL,
    business_externo_id VARCHAR(190) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    moeda CHAR(3) NULL,
    timezone VARCHAR(80) NULL,
    access_token_encrypted MEDIUMTEXT NULL,
    refresh_token_encrypted MEDIUMTEXT NULL,
    token_expires_at DATETIME NULL,
    config_json JSON NULL,
    ultimo_teste_em DATETIME NULL,
    ultima_sincronizacao_em DATETIME NULL,
    erro_ultima_sincronizacao TEXT NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_marketing_integracao_conta (provider,conta_externa_id),
    KEY idx_marketing_integracao_status (provider,status),
    CONSTRAINT fk_marketing_integracao_usuario FOREIGN KEY (created_by) REFERENCES usuarios_admin(id) ON DELETE SET NULL,
    CONSTRAINT chk_marketing_provider CHECK (provider IN ('META','GOOGLE','TIKTOK')),
    CONSTRAINT chk_marketing_integracao_status CHECK (status IN ('PENDENTE','CONECTADA','ERRO','EXPIRADA','DESCONECTADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_campanhas (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    integracao_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(16) NOT NULL,
    external_id VARCHAR(190) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    objetivo VARCHAR(120) NULL,
    status VARCHAR(80) NULL,
    data_inicio DATETIME NULL,
    data_fim DATETIME NULL,
    orcamento_diario DECIMAL(16,2) NULL,
    orcamento_total DECIMAL(16,2) NULL,
    moeda CHAR(3) NULL,
    dados_extras_json JSON NULL,
    last_synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_marketing_campanha (integracao_id,external_id),
    KEY idx_marketing_campanha_status (integracao_id,status),
    CONSTRAINT fk_marketing_campanha_integracao FOREIGN KEY (integracao_id) REFERENCES marketing_integracoes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_grupos_anuncios (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    integracao_id BIGINT UNSIGNED NOT NULL,
    campanha_id BIGINT UNSIGNED NULL,
    external_id VARCHAR(190) NOT NULL,
    campanha_external_id VARCHAR(190) NULL,
    nome VARCHAR(255) NOT NULL,
    status VARCHAR(80) NULL,
    orcamento DECIMAL(16,2) NULL,
    dados_extras_json JSON NULL,
    last_synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_marketing_grupo (integracao_id,external_id),
    KEY idx_marketing_grupo_campanha (campanha_id),
    CONSTRAINT fk_marketing_grupo_integracao FOREIGN KEY (integracao_id) REFERENCES marketing_integracoes(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_grupo_campanha FOREIGN KEY (campanha_id) REFERENCES marketing_campanhas(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_anuncios (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    integracao_id BIGINT UNSIGNED NOT NULL,
    grupo_anuncio_id BIGINT UNSIGNED NULL,
    external_id VARCHAR(190) NOT NULL,
    grupo_external_id VARCHAR(190) NULL,
    nome VARCHAR(255) NOT NULL,
    status VARCHAR(80) NULL,
    creative_name VARCHAR(255) NULL,
    creative_url VARCHAR(1000) NULL,
    dados_extras_json JSON NULL,
    last_synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_marketing_anuncio (integracao_id,external_id),
    KEY idx_marketing_anuncio_grupo (grupo_anuncio_id),
    CONSTRAINT fk_marketing_anuncio_integracao FOREIGN KEY (integracao_id) REFERENCES marketing_integracoes(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_anuncio_grupo FOREIGN KEY (grupo_anuncio_id) REFERENCES marketing_grupos_anuncios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_metricas_diarias (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    integracao_id BIGINT UNSIGNED NOT NULL,
    campanha_id BIGINT UNSIGNED NULL,
    grupo_anuncio_id BIGINT UNSIGNED NULL,
    anuncio_id BIGINT UNSIGNED NULL,
    provider VARCHAR(16) NOT NULL,
    nivel VARCHAR(16) NOT NULL,
    external_entity_id VARCHAR(190) NOT NULL,
    data DATE NOT NULL,
    moeda CHAR(3) NULL,
    gasto DECIMAL(16,2) NULL,
    impressoes BIGINT UNSIGNED NULL,
    alcance BIGINT UNSIGNED NULL,
    cliques BIGINT UNSIGNED NULL,
    conversoes DECIMAL(16,4) NULL,
    leads DECIMAL(16,4) NULL,
    valor_conversao DECIMAL(16,2) NULL,
    ctr DECIMAL(12,6) NULL,
    cpc DECIMAL(16,6) NULL,
    cpm DECIMAL(16,6) NULL,
    custo_por_lead DECIMAL(16,6) NULL,
    custo_por_conversao DECIMAL(16,6) NULL,
    frequencia DECIMAL(12,6) NULL,
    dados_extras_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_marketing_metrica (integracao_id,data,nivel,external_entity_id),
    KEY idx_marketing_metrica_dashboard (data,provider,integracao_id),
    KEY idx_marketing_metrica_campanha (campanha_id,data),
    CONSTRAINT fk_marketing_metrica_integracao FOREIGN KEY (integracao_id) REFERENCES marketing_integracoes(id) ON DELETE CASCADE,
    CONSTRAINT fk_marketing_metrica_campanha FOREIGN KEY (campanha_id) REFERENCES marketing_campanhas(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_metrica_grupo FOREIGN KEY (grupo_anuncio_id) REFERENCES marketing_grupos_anuncios(id) ON DELETE SET NULL,
    CONSTRAINT fk_marketing_metrica_anuncio FOREIGN KEY (anuncio_id) REFERENCES marketing_anuncios(id) ON DELETE SET NULL,
    CONSTRAINT chk_marketing_metrica_nivel CHECK (nivel IN ('CONTA','CAMPANHA','GRUPO','ANUNCIO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_sincronizacoes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    integracao_id BIGINT UNSIGNED NOT NULL,
    tipo VARCHAR(32) NOT NULL,
    data_inicio DATE NULL,
    data_fim DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    registros_processados INT UNSIGNED NOT NULL DEFAULT 0,
    registros_criados INT UNSIGNED NOT NULL DEFAULT 0,
    registros_atualizados INT UNSIGNED NOT NULL DEFAULT 0,
    erro TEXT NULL,
    lock_token CHAR(32) NULL,
    iniciada_em DATETIME NULL,
    finalizada_em DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_marketing_sync_integracao (integracao_id,created_at),
    KEY idx_marketing_sync_status (status,created_at),
    CONSTRAINT fk_marketing_sync_integracao FOREIGN KEY (integracao_id) REFERENCES marketing_integracoes(id) ON DELETE CASCADE,
    CONSTRAINT chk_marketing_sync_status CHECK (status IN ('PENDENTE','EXECUTANDO','CONCLUIDA','FALHOU','CANCELADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_atribuicoes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    lead_id BIGINT UNSIGNED NULL,
    cliente_id BIGINT UNSIGNED NULL,
    reserva_id BIGINT UNSIGNED NULL,
    conversa_id BIGINT UNSIGNED NULL,
    provider VARCHAR(16) NULL,
    utm_source VARCHAR(190) NULL,
    utm_medium VARCHAR(190) NULL,
    utm_campaign VARCHAR(190) NULL,
    utm_content VARCHAR(190) NULL,
    utm_term VARCHAR(190) NULL,
    gclid VARCHAR(255) NULL,
    gbraid VARCHAR(255) NULL,
    wbraid VARCHAR(255) NULL,
    fbclid VARCHAR(255) NULL,
    ttclid VARCHAR(255) NULL,
    landing_page VARCHAR(1000) NULL,
    referrer VARCHAR(1000) NULL,
    first_touch_json JSON NOT NULL,
    last_touch_json JSON NOT NULL,
    primeiro_contato_em DATETIME NOT NULL,
    ultimo_contato_em DATETIME NOT NULL,
    confianca VARCHAR(16) NOT NULL DEFAULT 'INDICATIVA',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_atribuicao_lead (lead_id),
    KEY idx_atribuicao_cliente (cliente_id),
    KEY idx_atribuicao_reserva (reserva_id),
    KEY idx_atribuicao_conversa (conversa_id),
    UNIQUE KEY uk_atribuicao_reserva (reserva_id),
    UNIQUE KEY uk_atribuicao_conversa (conversa_id),
    KEY idx_atribuicao_canal (utm_source,utm_campaign),
    CONSTRAINT fk_atribuicao_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL,
    CONSTRAINT fk_atribuicao_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL,
    CONSTRAINT fk_atribuicao_reserva FOREIGN KEY (reserva_id) REFERENCES reservas(id) ON DELETE CASCADE,
    CONSTRAINT fk_atribuicao_conversa FOREIGN KEY (conversa_id) REFERENCES conversas(id) ON DELETE SET NULL,
    CONSTRAINT chk_atribuicao_provider CHECK (provider IS NULL OR provider IN ('META','GOOGLE','TIKTOK','ORGANICO','DIRETO','OUTRO')),
    CONSTRAINT chk_atribuicao_confianca CHECK (confianca IN ('EXATA','PROVAVEL','INDICATIVA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
