<?php
declare(strict_types=1);

namespace Refugio\Marketing;

use Refugio\Support\Env;
use RuntimeException;

final class GoogleAdsProvider extends AbstractAdsProvider
{
    private function base():string{return'https://googleads.googleapis.com/'.rawurlencode(Env::get('GOOGLE_ADS_API_VERSION','v24'));}
    private function headers():array{$h=['Authorization: Bearer '.$this->accessToken,'developer-token: '.Env::get('GOOGLE_ADS_DEVELOPER_TOKEN')];$login=preg_replace('/\D/','',Env::get('GOOGLE_ADS_LOGIN_CUSTOMER_ID'));if($login)$h[]='login-customer-id: '.$login;return$h;}
    public function refreshCredentials():array{if($this->refreshToken==='')throw new RuntimeException('Refresh token do Google ausente.');$r=$this->http->form('https://oauth2.googleapis.com/token',['client_id'=>Env::get('GOOGLE_ADS_CLIENT_ID'),'client_secret'=>Env::get('GOOGLE_ADS_CLIENT_SECRET'),'refresh_token'=>$this->refreshToken,'grant_type'=>'refresh_token']);return['access_token'=>$r['access_token']??'','refresh_token'=>$this->refreshToken,'expires_at'=>date('Y-m-d H:i:s',time()+(int)($r['expires_in']??3600))];}
    public function listAccounts(?string $cursor=null):array{$r=$this->http->request('GET',$this->base().'/customers:listAccessibleCustomers',$this->headers());$items=[];foreach($r['resourceNames']??[]as$n){$id=basename((string)$n);$details=[];try{$details=$this->searchFor($id,'SELECT customer.id,customer.descriptive_name,customer.currency_code,customer.time_zone,customer.manager FROM customer LIMIT 1')['results'][0]['customer']??[];}catch(\Throwable){}$items[]=['external_id'=>$id,'name'=>$details['descriptiveName']??'Google Ads '.$id,'currency'=>$details['currencyCode']??null,'timezone'=>$details['timeZone']??null,'business_id'=>!empty($details['manager'])?$id:null,'raw'=>['resource_name'=>$n,'customer'=>$details]];}return self::page($items);}
    public function listCampaigns(?string $cursor=null):array{$query="SELECT campaign.id,campaign.name,campaign.status,campaign.advertising_channel_type,campaign.start_date,campaign.end_date,campaign_budget.amount_micros FROM campaign ORDER BY campaign.id";$r=$this->search($query,$cursor);$items=[];foreach($r['results']??[]as$row){$x=$row['campaign']??[];$items[]=['external_id'=>(string)($x['id']??''),'name'=>(string)($x['name']??$x['id']??''),'objective'=>$x['advertisingChannelType']??null,'status'=>$x['status']??null,'start_at'=>$this->date($x['startDate']??null),'end_at'=>$this->date($x['endDate']??null),'daily_budget'=>self::decimalFromMicros($row['campaignBudget']['amountMicros']??null),'total_budget'=>null,'currency'=>$this->integration['moeda']??null,'extra'=>$row];}return self::page($items,$r['nextPageToken']??null);}
    public function listAdGroups(?string $cursor=null):array{$r=$this->search('SELECT campaign.id,ad_group.id,ad_group.name,ad_group.status,ad_group.cpc_bid_micros FROM ad_group ORDER BY ad_group.id',$cursor);$items=[];foreach($r['results']??[]as$row){$x=$row['adGroup']??[];$items[]=['external_id'=>(string)($x['id']??''),'campaign_external_id'=>(string)($row['campaign']['id']??''),'name'=>(string)($x['name']??$x['id']??''),'status'=>$x['status']??null,'budget'=>self::decimalFromMicros($x['cpcBidMicros']??null),'extra'=>$row];}return self::page($items,$r['nextPageToken']??null);}
    public function listAds(?string $cursor=null):array{$r=$this->search('SELECT ad_group.id,ad_group_ad.ad.id,ad_group_ad.ad.name,ad_group_ad.status,ad_group_ad.ad.type,ad_group_ad.ad.final_urls FROM ad_group_ad ORDER BY ad_group_ad.ad.id',$cursor);$items=[];foreach($r['results']??[]as$row){$x=$row['adGroupAd']??[];$ad=$x['ad']??[];$items[]=['external_id'=>(string)($ad['id']??''),'group_external_id'=>(string)($row['adGroup']['id']??''),'name'=>(string)($ad['name']??($ad['type']??$ad['id']??'')),'status'=>$x['status']??null,'creative_name'=>$ad['name']??null,'creative_url'=>$ad['finalUrls'][0]??null,'extra'=>$row];}return self::page($items,$r['nextPageToken']??null);}
    public function getInsights(string $start,string $end,?string $cursor=null):array{$query="SELECT campaign.id,campaign.name,segments.date,customer.currency_code,metrics.cost_micros,metrics.impressions,metrics.clicks,metrics.ctr,metrics.average_cpc,metrics.conversions,metrics.cost_per_conversion,metrics.conversions_value FROM campaign WHERE segments.date BETWEEN '{$start}' AND '{$end}' ORDER BY segments.date,campaign.id";$r=$this->search($query,$cursor);$items=[];foreach($r['results']??[]as$row){$m=$row['metrics']??[];$items[]=['level'=>'CAMPANHA','external_entity_id'=>(string)($row['campaign']['id']??''),'campaign_external_id'=>(string)($row['campaign']['id']??''),'date'=>$row['segments']['date']??$start,'currency'=>$row['customer']['currencyCode']??$this->integration['moeda']??null,'spend'=>self::decimalFromMicros($m['costMicros']??null),'impressions'=>self::number($m['impressions']??null),'reach'=>null,'clicks'=>self::number($m['clicks']??null),'conversions'=>self::number($m['conversions']??null),'leads'=>null,'conversion_value'=>self::number($m['conversionsValue']??null),'ctr'=>isset($m['ctr'])?(string)((float)$m['ctr']*100):null,'cpc'=>self::decimalFromMicros($m['averageCpc']??null),'cpm'=>null,'cost_per_lead'=>null,'cost_per_conversion'=>self::decimalFromMicros($m['costPerConversion']??null),'frequency'=>null,'extra'=>$row];}return self::page($items,$r['nextPageToken']??null);}
    public function testConnection():bool{return$this->listAccounts()['items']!==[];}
    private function search(string$query,?string$cursor):array{return$this->searchFor(preg_replace('/\D/','',$this->accountId()),$query,$cursor);}
    private function searchFor(string$customer,string$query,?string$cursor=null):array{$body=['query'=>$query,'pageSize'=>1000];if($cursor)$body['pageToken']=$cursor;return$this->http->request('POST',$this->base().'/customers/'.$customer.'/googleAds:search',$this->headers(),[],$body);}
    private function date(?string$v):?string{if(!$v||strlen($v)!==8)return null;return substr($v,0,4).'-'.substr($v,4,2).'-'.substr($v,6,2).' 00:00:00';}
}
