<?php
declare(strict_types=1);

namespace Refugio\Marketing;

use Refugio\Support\Env;

final class MetaAdsProvider extends AbstractAdsProvider
{
    private function base():string{return'https://graph.facebook.com/'.rawurlencode(Env::get('META_API_VERSION','v24.0'));}
    private function get(string $path,array $query=[],?string $cursor=null):array{return$this->http->request('GET',$cursor&&str_starts_with($cursor,'https://')?$cursor:$this->base().'/'.ltrim($path,'/'),['Authorization: Bearer '.$this->accessToken],$cursor?[]:$query);}
    public function refreshCredentials():array{return['access_token'=>$this->accessToken,'refresh_token'=>$this->refreshToken,'expires_at'=>$this->integration['token_expires_at']??null];}
    public function listAccounts(?string $cursor=null):array{$r=$this->get('me/adaccounts',['fields'=>'id,account_id,name,currency,timezone_name,business{id,name}','limit'=>100],$cursor);return self::page(array_map(fn($x)=>['external_id'=>$x['id']??'','name'=>$x['name']??$x['id']??'','currency'=>$x['currency']??null,'timezone'=>$x['timezone_name']??null,'business_id'=>$x['business']['id']??null,'business_name'=>$x['business']['name']??null,'raw'=>$x],$r['data']??[]),$r['paging']['next']??null);}
    public function listCampaigns(?string $cursor=null):array{$r=$this->get($this->act().'/campaigns',['fields'=>'id,name,objective,status,effective_status,start_time,stop_time,daily_budget,lifetime_budget,buying_type,special_ad_categories','limit'=>100],$cursor);$items=[];foreach($r['data']??[]as$x)$items[]=['external_id'=>(string)$x['id'],'name'=>(string)($x['name']??$x['id']),'objective'=>$x['objective']??null,'status'=>$x['effective_status']??$x['status']??null,'start_at'=>$x['start_time']??null,'end_at'=>$x['stop_time']??null,'daily_budget'=>self::decimalFromMinor($x['daily_budget']??null),'total_budget'=>self::decimalFromMinor($x['lifetime_budget']??null),'currency'=>$this->integration['moeda']??null,'extra'=>$x];return self::page($items,$r['paging']['next']??null);}
    public function listAdGroups(?string $cursor=null):array{$r=$this->get($this->act().'/adsets',['fields'=>'id,campaign_id,name,status,effective_status,daily_budget,lifetime_budget,start_time,end_time','limit'=>100],$cursor);$items=[];foreach($r['data']??[]as$x)$items[]=['external_id'=>(string)$x['id'],'campaign_external_id'=>(string)($x['campaign_id']??''),'name'=>(string)($x['name']??$x['id']),'status'=>$x['effective_status']??$x['status']??null,'budget'=>self::decimalFromMinor($x['daily_budget']??$x['lifetime_budget']??null),'extra'=>$x];return self::page($items,$r['paging']['next']??null);}
    public function listAds(?string $cursor=null):array{$r=$this->get($this->act().'/ads',['fields'=>'id,adset_id,name,status,effective_status,creative{id,name,thumbnail_url}','limit'=>100],$cursor);$items=[];foreach($r['data']??[]as$x)$items[]=['external_id'=>(string)$x['id'],'group_external_id'=>(string)($x['adset_id']??''),'name'=>(string)($x['name']??$x['id']),'status'=>$x['effective_status']??$x['status']??null,'creative_name'=>$x['creative']['name']??null,'creative_url'=>$x['creative']['thumbnail_url']??null,'extra'=>$x];return self::page($items,$r['paging']['next']??null);}
    public function getInsights(string $start,string $end,?string $cursor=null):array{$fields='campaign_id,campaign_name,date_start,spend,impressions,reach,clicks,ctr,cpc,cpm,frequency,actions,action_values,cost_per_action_type';$r=$this->get($this->act().'/insights',['level'=>'campaign','time_increment'=>1,'time_range'=>json_encode(['since'=>$start,'until'=>$end]),'fields'=>$fields,'limit'=>100],$cursor);$items=[];foreach($r['data']??[]as$x){$leads=$this->actions($x['actions']??[],['lead','onsite_conversion.lead_grouped','offsite_conversion.fb_pixel_lead']);$conversions=$this->actions($x['actions']??[],['purchase','offsite_conversion.fb_pixel_purchase','booking']);$value=$this->actions($x['action_values']??[],['purchase','offsite_conversion.fb_pixel_purchase']);$items[]=['level'=>'CAMPANHA','external_entity_id'=>(string)($x['campaign_id']??''),'campaign_external_id'=>(string)($x['campaign_id']??''),'date'=>$x['date_start'],'currency'=>$this->integration['moeda']??null,'spend'=>self::number($x['spend']??null),'impressions'=>self::number($x['impressions']??null),'reach'=>self::number($x['reach']??null),'clicks'=>self::number($x['clicks']??null),'conversions'=>$conversions,'leads'=>$leads,'conversion_value'=>$value,'ctr'=>self::number($x['ctr']??null),'cpc'=>self::number($x['cpc']??null),'cpm'=>self::number($x['cpm']??null),'cost_per_lead'=>$this->cost($x['cost_per_action_type']??[],['lead','onsite_conversion.lead_grouped']),'cost_per_conversion'=>$this->cost($x['cost_per_action_type']??[],['purchase','booking']),'frequency'=>self::number($x['frequency']??null),'extra'=>$x];}return self::page($items,$r['paging']['next']??null);}
    public function testConnection():bool{$r=$this->get('me',['fields'=>'id']);return!empty($r['id']);}
    public function listAssets(string $accountId):array{$act=str_starts_with($accountId,'act_')?$accountId:'act_'.$accountId;$pages=[];$pixels=[];try{$r=$this->get($act.'/promote_pages',['fields'=>'id,name','limit'=>100]);$pages=$r['data']??[];}catch(\Throwable){}try{$r=$this->get($act.'/adspixels',['fields'=>'id,name,last_fired_time','limit'=>100]);$pixels=$r['data']??[];}catch(\Throwable){}return['pages'=>$pages,'pixels'=>$pixels];}
    private function act():string{$id=$this->accountId();return str_starts_with($id,'act_')?$id:'act_'.$id;}
    private function actions(array$rows,array$types):?string{$sum=0.0;$found=false;foreach($rows as$row)if(in_array($row['action_type']??'', $types,true)){$sum+=(float)($row['value']??0);$found=true;}return$found?rtrim(rtrim(number_format($sum,4,'.',''),'0'),'.'):null;}
    private function cost(array$rows,array$types):?string{foreach($rows as$row)if(in_array($row['action_type']??'',$types,true))return self::number($row['value']??null);return null;}
}
