<?php
declare(strict_types=1);

namespace Refugio\Marketing;

use Refugio\Support\Env;
use RuntimeException;

final class TikTokAdsProvider extends AbstractAdsProvider
{
    private function base():string{return'https://business-api.tiktok.com/open_api/'.rawurlencode(Env::get('TIKTOK_API_VERSION','v1.3'));}
    private function get(string$path,array$query=[]):array{$r=$this->http->request('GET',$this->base().'/'.ltrim($path,'/'),['Access-Token: '.$this->accessToken],$query);if((int)($r['code']??0)!==0)throw new RuntimeException('TikTok recusou a requisicao: '.mb_substr((string)($r['message']??'erro'),0,500));return$r['data']??[];}
    public function refreshCredentials():array{if($this->refreshToken==='')return['access_token'=>$this->accessToken,'refresh_token'=>'','expires_at'=>$this->integration['token_expires_at']??null];$r=$this->http->form($this->base().'/tt_user/oauth2/refresh_token/',['client_key'=>Env::get('TIKTOK_ADS_APP_ID'),'client_secret'=>Env::get('TIKTOK_ADS_APP_SECRET'),'grant_type'=>'refresh_token','refresh_token'=>$this->refreshToken]);return['access_token'=>$r['data']['access_token']??$r['access_token']??'','refresh_token'=>$r['data']['refresh_token']??$this->refreshToken,'expires_at'=>date('Y-m-d H:i:s',time()+(int)($r['data']['expires_in']??86400))];}
    public function listAccounts(?string$cursor=null):array{$data=$this->get('oauth2/advertiser/get/',['app_id'=>Env::get('TIKTOK_ADS_APP_ID'),'secret'=>Env::get('TIKTOK_ADS_APP_SECRET')]);$items=[];foreach($data['list']??[]as$x)$items[]=['external_id'=>(string)($x['advertiser_id']??''),'name'=>(string)($x['advertiser_name']??$x['advertiser_id']??''),'currency'=>$x['currency']??null,'timezone'=>$x['timezone']??null,'business_id'=>$x['bc_id']??null,'raw'=>$x];return self::page($items);}
    public function listCampaigns(?string$cursor=null):array{$page=max(1,(int)($cursor?:1));$d=$this->get('campaign/get/',['advertiser_id'=>$this->accountId(),'page'=>$page,'page_size'=>100]);$items=[];foreach($d['list']??[]as$x)$items[]=['external_id'=>(string)$x['campaign_id'],'name'=>(string)($x['campaign_name']??$x['campaign_id']),'objective'=>$x['objective_type']??null,'status'=>$x['operation_status']??$x['secondary_status']??null,'start_at'=>null,'end_at'=>null,'daily_budget'=>self::number($x['budget']??null),'total_budget'=>null,'currency'=>$this->integration['moeda']??null,'extra'=>$x];return self::page($items,$this->next($d,$page));}
    public function listAdGroups(?string$cursor=null):array{$page=max(1,(int)($cursor?:1));$d=$this->get('adgroup/get/',['advertiser_id'=>$this->accountId(),'page'=>$page,'page_size'=>100]);$items=[];foreach($d['list']??[]as$x)$items[]=['external_id'=>(string)$x['adgroup_id'],'campaign_external_id'=>(string)($x['campaign_id']??''),'name'=>(string)($x['adgroup_name']??$x['adgroup_id']),'status'=>$x['operation_status']??$x['secondary_status']??null,'budget'=>self::number($x['budget']??null),'extra'=>$x];return self::page($items,$this->next($d,$page));}
    public function listAds(?string$cursor=null):array{$page=max(1,(int)($cursor?:1));$d=$this->get('ad/get/',['advertiser_id'=>$this->accountId(),'page'=>$page,'page_size'=>100]);$items=[];foreach($d['list']??[]as$x)$items[]=['external_id'=>(string)$x['ad_id'],'group_external_id'=>(string)($x['adgroup_id']??''),'name'=>(string)($x['ad_name']??$x['ad_id']),'status'=>$x['operation_status']??$x['secondary_status']??null,'creative_name'=>$x['ad_name']??null,'creative_url'=>$x['landing_page_url']??null,'extra'=>$x];return self::page($items,$this->next($d,$page));}
    public function getInsights(string$start,string$end,?string$cursor=null):array{$page=max(1,(int)($cursor?:1));$query=['advertiser_id'=>$this->accountId(),'report_type'=>'BASIC','data_level'=>'AUCTION_CAMPAIGN','dimensions'=>json_encode(['campaign_id','stat_time_day']),'metrics'=>json_encode(['campaign_name','spend','impressions','reach','clicks','ctr','cpc','cpm','conversion','cost_per_conversion','real_time_conversion','total_purchase_value','frequency']),'start_date'=>$start,'end_date'=>$end,'page'=>$page,'page_size'=>1000];$d=$this->get('report/integrated/get/',$query);$items=[];foreach($d['list']??[]as$row){$x=array_merge($row['dimensions']??[],$row['metrics']??[]);$items[]=['level'=>'CAMPANHA','external_entity_id'=>(string)($x['campaign_id']??''),'campaign_external_id'=>(string)($x['campaign_id']??''),'date'=>substr((string)($x['stat_time_day']??$start),0,10),'currency'=>$this->integration['moeda']??null,'spend'=>self::number($x['spend']??null),'impressions'=>self::number($x['impressions']??null),'reach'=>self::number($x['reach']??null),'clicks'=>self::number($x['clicks']??null),'conversions'=>self::number($x['conversion']??$x['real_time_conversion']??null),'leads'=>self::number($x['lead']??null),'conversion_value'=>self::number($x['total_purchase_value']??null),'ctr'=>self::number($x['ctr']??null),'cpc'=>self::number($x['cpc']??null),'cpm'=>self::number($x['cpm']??null),'cost_per_lead'=>self::number($x['cost_per_lead']??null),'cost_per_conversion'=>self::number($x['cost_per_conversion']??null),'frequency'=>self::number($x['frequency']??null),'extra'=>$row];}return self::page($items,$this->next($d,$page));}
    public function testConnection():bool{return$this->listAccounts()['items']!==[];}
    public function listAssets(string $advertiserId):array{$pixels=[];try{$data=$this->get('pixel/list/',['advertiser_id'=>$advertiserId]);$pixels=$data['pixels']??$data['list']??[];}catch(\Throwable){}return['pages'=>[],'pixels'=>$pixels];}
    private function next(array$d,int$page):?string{$info=$d['page_info']??[];$total=(int)($info['total_page']??$info['total_pages']??1);return$page<$total?(string)($page+1):null;}
}
