<?php
declare(strict_types=1);

namespace Refugio\Controllers;

use DateTimeImmutable;
use Refugio\Config\Database;
use Refugio\Marketing\MarketingProviderFactory;
use Refugio\Repositories\MarketingRepository;
use Refugio\Services\AuditService;
use Refugio\Services\AuthorizationService;
use Refugio\Services\JobQueueService;
use Refugio\Services\MarketingOAuthService;
use Refugio\Services\MarketingSyncService;
use Refugio\Support\Csrf;
use Refugio\Support\Env;
use RuntimeException;
use Throwable;

final class MarketingController
{
    private \PDO$db;private MarketingRepository$repository;
    public function __construct(private array$config){}
    public function index():void{AuthorizationService::requirePermission('marketing.view');$this->boot();[$start,$end]=$this->period();$filters=array_intersect_key($_GET,array_flip(['provider','integracao_id','campanha_id','modelo']));$dashboard=$this->repository->dashboard($start,$end,$filters);$integrations=$this->repository->integrations();$campaigns=$this->repository->campaigns($filters);require BASE_PATH.'/app/Views/admin/marketing.php';}
    public function connect(string$provider):never{AuthorizationService::requirePermission('marketing.connect');try{if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')throw new RuntimeException('Use o formulario protegido para iniciar a conexao.');Csrf::verify($_POST['_csrf']??null);$url=(new MarketingOAuthService($this->config))->authorizationUrl(strtoupper($provider));redirect($url);}catch(Throwable$e){flash('error',$e->getMessage());redirect(base_url('admin/marketing'));}}
    public function callback(string$provider):never{AuthorizationService::requirePermission('marketing.connect');$this->boot();try{if(!empty($_GET['error']))throw new RuntimeException('Autorizacao recusada pelo provedor.');$tokens=(new MarketingOAuthService($this->config))->exchange(strtoupper($provider),(string)($_GET['code']??$_GET['auth_code']??''),(string)($_GET['state']??''));$id=$this->repository->createIntegration(strtoupper($provider),$tokens,(int)$_SESSION['admin_id']);(new AuditService($this->db))->record('MARKETING','CONECTAR_OAUTH','marketing_integracoes',$id,null,['provider'=>strtoupper($provider)]);redirect(base_url('admin/marketing/contas?integracao='.$id));}catch(Throwable$e){flash('error',$e->getMessage());redirect(base_url('admin/marketing'));}}
    public function accounts(int$id):void{AuthorizationService::requirePermission('marketing.connect');$this->boot();$integration=$this->repository->findIntegration($id)??throw new RuntimeException('Integracao nao encontrada.');$provider=MarketingProviderFactory::make($integration);$accounts=[];$cursor=null;$pages=0;do{$page=$provider->listAccounts($cursor);$accounts=array_merge($accounts,$page['items']??[]);$cursor=$page['next_cursor']??null;$pages++;}while($cursor&&$pages<20);$assets=['pages'=>[],'pixels'=>[]];if(count($accounts)===1&&method_exists($provider,'listAssets'))$assets=$provider->listAssets((string)$accounts[0]['external_id']);require BASE_PATH.'/app/Views/admin/marketing-accounts.php';}
    public function selectAccount(int$id):never{AuthorizationService::requirePermission('marketing.connect');$this->boot();try{Csrf::verify($_POST['_csrf']??null);$integration=$this->repository->findIntegration($id)??throw new RuntimeException('Integracao nao encontrada.');$wanted=(string)($_POST['conta_externa_id']??'');$provider=MarketingProviderFactory::make($integration);$account=null;$cursor=null;$pages=0;do{$page=$provider->listAccounts($cursor);foreach($page['items']??[]as$item)if(hash_equals((string)$item['external_id'],$wanted)){$account=$item;break 2;}$cursor=$page['next_cursor']??null;$pages++;}while($cursor&&$pages<20);if(!$account)throw new RuntimeException('Conta de anuncios nao autorizada.');$config=[];if(method_exists($provider,'listAssets')){$assets=$provider->listAssets($wanted);foreach(['page_external_id'=>'pages','pixel_external_id'=>'pixels']as$field=>$group){$selected=(string)($_POST[$field]??'');if($selected!==''){$allowed=false;foreach($assets[$group]??[]as$asset){$assetId=(string)($asset['id']??$asset['pixel_id']??'');if(hash_equals($assetId,$selected)){$allowed=true;break;}}if(!$allowed)throw new RuntimeException('Ativo adicional nao autorizado para esta conta.');$config[$field]=$selected;}}}$this->repository->selectAccount($id,$account,$config);(new AuditService($this->db))->record('MARKETING','SELECIONAR_CONTA','marketing_integracoes',$id,null,['conta'=>$account['external_id'],'provider'=>$integration['provider'],'ativos'=>$config]);flash('success','Conta conectada. A primeira sincronizacao pode ser iniciada.');}catch(Throwable$e){flash('error',$e->getMessage());}redirect(base_url('admin/marketing'));}
    public function action(int$id,string$action):never{AuthorizationService::requirePermission($action==='desconectar'?'marketing.connect':'marketing.sync');$this->boot();try{Csrf::verify($_POST['_csrf']??null);if($action==='sincronizar'){$days=max(1,min(366,Env::int('MARKETING_SYNC_DAYS_DEFAULT',30)));$start=(string)($_POST['inicio']??date('Y-m-d',strtotime('-'.($days-1).' days')));$end=(string)($_POST['fim']??date('Y-m-d'));$key='marketing-sync-'.$id.'-'.$start.'-'.$end.'-'.date('YmdHi');(new JobQueueService($this->db))->enqueue('MARKETING_SYNC',['integration_id'=>$id,'start'=>$start,'end'=>$end,'user_id'=>(int)$_SESSION['admin_id']],$key,40,5);flash('success','Sincronizacao adicionada a fila.');}elseif($action==='testar'){(new MarketingSyncService($this->db))->test($id,(int)$_SESSION['admin_id']);flash('success','Conexao validada com sucesso.');}elseif($action==='desconectar'){$this->repository->disconnect($id);(new AuditService($this->db))->record('MARKETING','DESCONECTAR','marketing_integracoes',$id);flash('success','Integracao desconectada e credenciais removidas.');}else throw new RuntimeException('Acao de marketing invalida.');}catch(Throwable$e){flash('error',$e->getMessage());}redirect(base_url('admin/marketing'));}
    private function period():array{$preset=(string)($_GET['periodo']??'30d');$today=new DateTimeImmutable('today');[$start,$end]=match($preset){'hoje'=>[$today,$today],'ontem'=>[$today->modify('-1 day'),$today->modify('-1 day')],'7d'=>[$today->modify('-6 days'),$today],'mes'=>[$today->modify('first day of this month'),$today],'mes-anterior'=>[$today->modify('first day of last month'),$today->modify('last day of last month')],default=>[$today->modify('-29 days'),$today]};if(!empty($_GET['inicio'])&&!empty($_GET['fim'])){try{$a=new DateTimeImmutable((string)$_GET['inicio']);$b=new DateTimeImmutable((string)$_GET['fim']);if($b>=$a&&$b<=$a->modify('+366 days')){$start=$a;$end=$b;}}catch(Throwable){}}return[$start->format('Y-m-d'),$end->format('Y-m-d')];}
    private function boot():void{if(isset($this->db))return;$this->db=Database::connection();$this->repository=new MarketingRepository($this->db);}
}
