<?php
declare(strict_types=1);
$config = require dirname(__DIR__) . '/bootstrap.php';
$type = (string) ($_GET['tipo'] ?? 'privacidade');
$pages = [
    'privacidade' => ['Politica de privacidade', '<p>Coletamos nome, contato, datas, quantidade de hospedes e, quando informado, CPF, exclusivamente para analisar a solicitacao, organizar a hospedagem, processar pagamentos e manter comunicacoes relacionadas.</p><p>Os dados sao acessados apenas por pessoas autorizadas e fornecedores essenciais de e-mail e WhatsApp. Mantemos os registros pelo periodo necessario ao cumprimento das finalidades e obrigacoes legais. Voce pode solicitar acesso, correcao ou eliminacao pelo e-mail <a href="mailto:refugiodocuscuzeiro@gmail.com">refugiodocuscuzeiro@gmail.com</a>.</p><p>Esta pagina e um texto inicial editavel. Antes da publicacao, o responsavel deve revisar prazos de retencao, bases legais e identificacao do controlador com orientacao juridica.</p>'],
    'termos' => ['Termos da reserva', '<p>O envio do formulario cria uma <strong>solicitacao de reserva</strong>, nao uma reserva confirmada. A disponibilidade sera analisada manualmente.</p><p>A reserva somente sera confirmada depois da aprovacao, identificacao do pagamento e confirmacao expressa enviada pelo Refugio do Cuscuzeiro. Valores, prazos, horarios e demais condicoes serao apresentados antes do pagamento.</p><p>Este texto e editavel e deve ser revisado pelo responsavel antes da publicacao.</p>'],
    'cancelamento' => ['Politica de cancelamento', '<p>As condicoes de cancelamento aplicaveis serao informadas na aprovacao da solicitacao e exibidas na pagina de pagamento. Em caso de necessidade, entre em contato o quanto antes.</p><p>Reembolsos, creditos ou retencoes dependem do prazo, dos custos assumidos e das condicoes expressamente aceitas para a reserva.</p><p>Este texto e um modelo inicial. Substitua-o pela politica comercial e juridica definitiva antes da publicacao.</p>'],
    'regras' => ['Regras da propriedade', '<p>Respeite o limite de hospedes informado, os horarios combinados, a vizinhanca, as areas de lazer e as orientacoes de seguranca entregues antes do check-in.</p><p>Eventos, visitantes adicionais, animais e equipamentos especiais precisam de autorizacao previa. Danos e descumprimentos poderao gerar cobranca conforme as condicoes aceitas.</p><p>Este texto e um resumo inicial editavel. O responsavel deve inserir aqui as regras completas da propriedade antes da publicacao.</p>'],
];
if (!isset($pages[$type])) { http_response_code(404); $type='privacidade'; }
[$heading,$content]=$pages[$type]; $title=$heading; require BASE_PATH.'/app/Views/public/_top.php';
?><article class="reservation-card policy-page"><div class="eyebrow">Informacoes importantes</div><h1><?= e($heading) ?></h1><?= $content ?><a class="secondary-button inline" href="<?= e(base_url('reserva/solicitar')) ?>">Voltar</a></article><?php require BASE_PATH.'/app/Views/public/_bottom.php'; ?>
