<?php $title='Minha reserva '.$portal['code'];require BASE_PATH.'/app/Views/public/_top.php';?>
<section class="reservation-card portal-hero"><p class="eyebrow">Minha reserva</p><h1>Olá, <?= e($portal['guest_first_name']) ?></h1><p>Acompanhe cada etapa da estadia <strong><?= e($portal['code']) ?></strong>.</p><?php if($message=flash('success')):?><div class="alert alert-success"><?= e($message) ?></div><?php endif;?><?php if($message=flash('error')):?><div class="alert alert-error"><?= e($message) ?></div><?php endif;?></section>
<section class="reservation-card"><h2>Jornada</h2><ol class="portal-timeline"><?php foreach($portal['timeline'] as $step):?><li class="<?= $step['done']?'done':'' ?>"><span><?= $step['done']?'✓':'○' ?></span><?= e($step['label']) ?></li><?php endforeach;?></ol></section>
<section class="reservation-card"><h2>Resumo</h2><dl class="summary summary-grid"><div><dt>Check-in</dt><dd><?= date('d/m/Y',strtotime($portal['checkin'])) ?></dd></div><div><dt>Check-out</dt><dd><?= date('d/m/Y',strtotime($portal['checkout'])) ?></dd></div><div><dt>Hóspedes</dt><dd><?= (int)$portal['guests'] ?></dd></div><div><dt>Valor</dt><dd><?= money($portal['total']) ?></dd></div></dl></section>
<section class="reservation-card"><h2>Pagamentos</h2><?php if(!$portal['payments']):?><p>Nenhuma cobrança disponível.</p><?php endif;?><?php foreach($portal['payments'] as $payment):?><div class="portal-row"><strong><?= e($payment['tipo']) ?> · <?= money($payment['valor']) ?></strong><span class="status-badge"><?= e($payment['status']) ?></span></div><?php endforeach;?></section>
<?php if($portal['contract']):?><section class="reservation-card" id="contrato"><h2>Contrato</h2><p>Status: <strong><?= e($portal['contract']['status']) ?></strong></p><?php if($portal['contract']['pdf_path']):?><p><a class="secondary-button inline" href="<?= e(base_url('minha-reserva/'.rawurlencode($token).'/contrato.pdf')) ?>" target="_blank">Abrir PDF íntegro</a></p><?php endif;?><?php if(!in_array($portal['contract']['status'],['SIGNED_BY_GUEST','FULLY_SIGNED'],true)):?><form action="<?= e(base_url('minha-reserva/'.rawurlencode($token).'/contrato/codigo')) ?>" method="post"><?= csrf_field() ?><button class="secondary-button">Enviar código de assinatura</button></form><form class="admin-form" action="<?= e(base_url('minha-reserva/'.rawurlencode($token).'/contrato/assinar')) ?>" method="post"><?= csrf_field() ?><label>Nome completo<input name="name" required></label><label>CPF<input name="cpf" inputmode="numeric" required></label><label>Código recebido<input name="code" inputmode="numeric" maxlength="6" required></label><label><input type="checkbox" name="accepted" value="1" required> Li o documento integralmente e concordo com seu conteúdo.</label><button class="primary-button">Registrar aceite</button></form><?php endif;?></section><?php endif;?>
<?php if($portal['precheckin']):?><section class="reservation-card"><h2>Pré-check-in</h2><p>Status: <strong><?= e($portal['precheckin']['status']) ?></strong></p><a class="primary-button inline" href="<?= e(base_url(ltrim($portal['precheckin_path'],'/'))) ?>">Abrir pré-check-in</a></section><?php endif;?>
<?php if($portal['arrival']):?><section class="reservation-card"><h2>Chegada</h2><p><strong>Endereço:</strong> <?= e($portal['arrival']['address']) ?></p><p><?= nl2br(e($portal['arrival']['directions'])) ?></p><p><strong>Acesso:</strong> <?= nl2br(e($portal['arrival']['access'])) ?></p><p><strong>Wi-Fi:</strong> <?= e($portal['arrival']['wifi_name']) ?> · <?= e($portal['arrival']['wifi_password']) ?></p><p><strong>Emergência:</strong> <?= e($portal['arrival']['emergency_contact']) ?></p></section><?php else:?><section class="reservation-card"><h2>Instruções de chegada</h2><p>Serão liberadas perto do check-in quando pagamento, contrato e pré-check-in atenderem às regras configuradas.</p></section><?php endif;?>
<?php require BASE_PATH.'/app/Views/public/_bottom.php';?>
