<?php
declare(strict_types=1);

namespace Refugio\Repositories;

use PDO;
use Refugio\Services\EncryptionService;
use Refugio\Support\MarketingMetrics;

final class MarketingRepository
{
    public function __construct(private PDO$db){}
    public function integrations(bool$includeSecrets=false):array{$fields=$includeSecrets?'*':'id,provider,nome,conta_externa_id,business_externo_id,status,moeda,timezone,token_expires_at,config_json,ultimo_teste_em,ultima_sincronizacao_em,erro_ultima_sincronizacao,created_by,created_at,updated_at';return$this->db->query("SELECT {$fields} FROM marketing_integracoes ORDER BY provider,nome")->fetchAll();}
    public function findIntegration(int$id):?array{$s=$this->db->prepare('SELECT * FROM marketing_integracoes WHERE id=?');$s->execute([$id]);return$s->fetch()?:null;}
    public function createIntegration(string$provider,array$tokens,int$userId):int{$enc=new EncryptionService();$s=$this->db->prepare("INSERT INTO marketing_integracoes (provider,nome,status,access_token_encrypted,refresh_token_encrypted,token_expires_at,created_by) VALUES (?,?, 'PENDENTE',?,?,?,?)");$s->execute([$provider,ucfirst(strtolower($provider)).' Ads',$enc->encrypt((string)$tokens['access_token']),$enc->encrypt((string)($tokens['refresh_token']??'')),$tokens['expires_at']??null,$userId]);return(int)$this->db->lastInsertId();}
    public function selectAccount(int$id,array$account,array$config=[]):void{$existing=$this->findIntegration($id);$merged=array_replace(json_decode((string)($existing['config_json']??'{}'),true)?:[],$config,['account'=>$account]);$this->db->prepare("UPDATE marketing_integracoes SET conta_externa_id=?,business_externo_id=?,nome=?,moeda=?,timezone=?,config_json=?,status='CONECTADA',erro_ultima_sincronizacao=NULL WHERE id=?")->execute([$account['external_id'],$account['business_id']??null,$account['name']??$existing['nome'],$account['currency']??null,$account['timezone']??null,json_encode($merged,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$id]);}
    public function updateCredentials(int$id,array$tokens):void{$enc=new EncryptionService();$this->db->prepare('UPDATE marketing_integracoes SET access_token_encrypted=?,refresh_token_encrypted=?,token_expires_at=?,status=\'CONECTADA\' WHERE id=?')->execute([$enc->encrypt((string)$tokens['access_token']),$enc->encrypt((string)($tokens['refresh_token']??'')),$tokens['expires_at']??null,$id]);}
    public function disconnect(int$id):void{$this->db->prepare("UPDATE marketing_integracoes SET access_token_encrypted=NULL,refresh_token_encrypted=NULL,token_expires_at=NULL,status='DESCONECTADA' WHERE id=?")->execute([$id]);}
    public function campaigns(array$filters=[]):array{$where=['1=1'];$params=[];if(!empty($filters['provider'])){$where[]='c.provider=?';$params[]=$filters['provider'];}if(!empty($filters['integracao_id'])){$where[]='c.integracao_id=?';$params[]=(int)$filters['integracao_id'];}$s=$this->db->prepare('SELECT c.*,i.nome integracao_nome FROM marketing_campanhas c JOIN marketing_integracoes i ON i.id=c.integracao_id WHERE '.implode(' AND ',$where).' ORDER BY c.updated_at DESC LIMIT 300');$s->execute($params);return$s->fetchAll();}
    public function dashboard(string$start,string$end,array$filters=[]):array
    {
        $where=['m.data BETWEEN ? AND ?','m.nivel=\'CAMPANHA\''];$params=[$start,$end];if(!empty($filters['provider'])){$where[]='m.provider=?';$params[]=$filters['provider'];}if(!empty($filters['integracao_id'])){$where[]='m.integracao_id=?';$params[]=(int)$filters['integracao_id'];}if(!empty($filters['campanha_id'])){$where[]='m.campanha_id=?';$params[]=(int)$filters['campanha_id'];}$w=implode(' AND ',$where);
        $s=$this->db->prepare("SELECT COALESCE(SUM(gasto),0) gasto,SUM(impressoes) impressoes,SUM(alcance) alcance,SUM(cliques) cliques,SUM(conversoes) conversoes,SUM(leads) leads,SUM(valor_conversao) valor_conversao FROM marketing_metricas_diarias m WHERE {$w}");$s->execute($params);$metrics=$s->fetch();
        $daily=$this->db->prepare("SELECT data,provider,SUM(gasto) gasto,SUM(leads) leads,SUM(cliques) cliques FROM marketing_metricas_diarias m WHERE {$w} GROUP BY data,provider ORDER BY data,provider");$daily->execute($params);
        $channels=$this->db->prepare("SELECT provider,SUM(gasto) gasto,SUM(impressoes) impressoes,SUM(cliques) cliques,SUM(leads) leads,SUM(conversoes) conversoes FROM marketing_metricas_diarias m WHERE {$w} GROUP BY provider ORDER BY gasto DESC");$channels->execute($params);
        $firstProvider="CASE WHEN JSON_UNQUOTE(JSON_EXTRACT(a.first_touch_json,'$.gclid')) IS NOT NULL OR JSON_UNQUOTE(JSON_EXTRACT(a.first_touch_json,'$.gbraid')) IS NOT NULL OR JSON_UNQUOTE(JSON_EXTRACT(a.first_touch_json,'$.wbraid')) IS NOT NULL THEN 'GOOGLE' WHEN JSON_UNQUOTE(JSON_EXTRACT(a.first_touch_json,'$.fbclid')) IS NOT NULL THEN 'META' WHEN JSON_UNQUOTE(JSON_EXTRACT(a.first_touch_json,'$.ttclid')) IS NOT NULL THEN 'TIKTOK' WHEN LOWER(JSON_UNQUOTE(JSON_EXTRACT(a.first_touch_json,'$.utm_source'))) REGEXP 'google' THEN 'GOOGLE' WHEN LOWER(JSON_UNQUOTE(JSON_EXTRACT(a.first_touch_json,'$.utm_source'))) REGEXP 'facebook|instagram|meta' THEN 'META' WHEN LOWER(JSON_UNQUOTE(JSON_EXTRACT(a.first_touch_json,'$.utm_source'))) REGEXP 'tiktok' THEN 'TIKTOK' ELSE COALESCE(a.provider,'DIRETO') END";
        $providerExpression=($filters['modelo']??'ultimo')==='primeiro'?$firstProvider:'a.provider';$attrWhere=['a.created_at BETWEEN ? AND DATE_ADD(?,INTERVAL 1 DAY)'];$attrParams=[$start,$end];if(!empty($filters['provider'])){$attrWhere[]="{$providerExpression}=?";$attrParams[]=$filters['provider'];}if(!empty($filters['campanha_id'])){$campaign=$this->db->prepare('SELECT nome FROM marketing_campanhas WHERE id=?');$campaign->execute([(int)$filters['campanha_id']]);$campaignName=$campaign->fetchColumn();if($campaignName){$attrWhere[]='a.utm_campaign=?';$attrParams[]=$campaignName;}}$aw=implode(' AND ',$attrWhere);
        $a=$this->db->prepare("SELECT COUNT(DISTINCT a.lead_id) leads_internos,COUNT(DISTINCT a.reserva_id) solicitacoes,COUNT(DISTINCT CASE WHEN r.status IN ('RESERVA_CONFIRMADA','FINALIZADA') THEN r.id END) reservas_confirmadas,COALESCE(SUM(p.receita),0) receita FROM marketing_atribuicoes a LEFT JOIN reservas r ON r.id=a.reserva_id LEFT JOIN (SELECT reserva_id,SUM(valor) receita FROM pagamentos WHERE status='CONFIRMADO' GROUP BY reserva_id) p ON p.reserva_id=r.id WHERE {$aw}");$a->execute($attrParams);$attribution=$a->fetch();
        $attributionDaily=$this->db->prepare("SELECT DATE(a.created_at) data,COUNT(DISTINCT CASE WHEN r.status IN ('RESERVA_CONFIRMADA','FINALIZADA') THEN r.id END) reservas,COALESCE(SUM(p.receita),0) receita FROM marketing_atribuicoes a LEFT JOIN reservas r ON r.id=a.reserva_id LEFT JOIN (SELECT reserva_id,SUM(valor) receita FROM pagamentos WHERE status='CONFIRMADO' GROUP BY reserva_id) p ON p.reserva_id=r.id WHERE {$aw} GROUP BY DATE(a.created_at) ORDER BY data");$attributionDaily->execute($attrParams);
        $spend=$metrics['gasto']??0;$leads=(float)($attribution['leads_internos']?:$metrics['leads']?:0);$reservations=(int)$attribution['reservas_confirmadas'];$metrics['ctr']=MarketingMetrics::divide(($metrics['cliques']??0)*100,$metrics['impressoes']??0);$metrics['cpc']=MarketingMetrics::divide($spend,$metrics['cliques']??0);$metrics['cpm']=MarketingMetrics::divide(($spend??0)*1000,$metrics['impressoes']??0);$metrics['cpl']=MarketingMetrics::cpl($spend,$leads);$metrics['custo_reserva']=MarketingMetrics::costPerReservation($spend,$reservations);$metrics['roas']=MarketingMetrics::roas($attribution['receita'],$spend);$metrics['taxa_conversao']=MarketingMetrics::conversionRate($reservations,$leads);
        return['metrics'=>$metrics,'attribution'=>$attribution,'daily'=>$daily->fetchAll(),'attribution_daily'=>$attributionDaily->fetchAll(),'channels'=>$channels->fetchAll()];
    }
}
